import type { Place } from "./types";

export const TRIP_META = {
  start: "9 июня 2026",
  end: "8 июля 2026",
  totalNights: 29,
  travelers: 2,
  workingHours: "с 14:00 до ночи по будням",
};

// Главные точки маршрута (для карты)
export const ROUTE_POINTS = [
  "Seminyak, Bali, Indonesia",
  "Ubud, Bali, Indonesia",
  "Sidemen, Karangasem, Bali, Indonesia",
  "Kintamani, Bangli, Bali, Indonesia",
  "Amed, Karangasem, Bali, Indonesia",
  "Lovina Beach, Buleleng, Bali, Indonesia",
  "Pemuteran, Buleleng, Bali, Indonesia",
  "Munduk, Buleleng, Bali, Indonesia",
  "Jatiluwih, Tabanan, Bali, Indonesia",
  "Seminyak, Bali, Indonesia",
];

// Координаты каждой локации (lat, lon) — для карты в app
export const PLACE_COORDS: Record<string, { lat: number; lon: number }> = {
  seminyak: { lat: -8.6898, lon: 115.1711 },
  ubud: { lat: -8.5069, lon: 115.2625 },
  sidemen: { lat: -8.4556, lon: 115.4492 },
  kintamani: { lat: -8.2778, lon: 115.3525 },
  amed: { lat: -8.3400, lon: 115.6864 },
  lovina: { lat: -8.1583, lon: 115.0283 },
  pemuteran: { lat: -8.1425, lon: 114.6517 },
  munduk: { lat: -8.2628, lon: 115.0681 },
  jatiluwih: { lat: -8.3706, lon: 115.1367 },
};

// Bounding box Бали (для OSM embed)
export const BALI_BBOX = "114.40,-8.87,115.72,-8.03";

export const PLACES: Place[] = [
  // =========================================================
  {
    slug: "ubud",
    name: "Убуд",
    nights: 5,
    dates: "9–13 июня",
    summary: "Лес обезьян, рисовые террасы, Cretya, водопады, йога",
    emoji: "🌿",
    color: "jungle",
    spots: [
      { name: "Monkey Forest", desc: "Лес обезьян. Открытие 9:00, к 10 народ. Прячь очки и телефоны", mapQuery: "Sacred Monkey Forest Sanctuary Ubud", tag: "парк", time: "утро", cost: "80k IDR" },
      { name: "Tegalalang Rice Terraces", desc: "Классика рисовых террас. К 8:00 без толпы", mapQuery: "Tegalalang Rice Terrace", tag: "природа", time: "утро", cost: "25k IDR" },
      { name: "Campuhan Ridge Walk", desc: "Лёгкий трек по холму, 1 час, бесплатно", mapQuery: "Campuhan Ridge Walk Ubud", tag: "прогулка", time: "утро/закат" },
      { name: "Tibumana Waterfall", desc: "Один красивый водопад, озерцо для купания, 45 мин от Убуда", mapQuery: "Tibumana Waterfall", tag: "водопад", cost: "20k IDR" },
      { name: "Tegenungan Waterfall", desc: "Ближе к Убуду, более туристический", mapQuery: "Tegenungan Waterfall", tag: "водопад", cost: "20k IDR" },
      { name: "Cretya Ubud Day Club", desc: "Бассейн, коктейли, идеально на закат", mapQuery: "Cretya Ubud", tag: "day club", time: "с обеда до заката", cost: "300k+ minimum spend" },
      { name: "Yoga Barn", desc: "Культовая йога-студия, классы с 7:30", mapQuery: "The Yoga Barn Ubud", tag: "йога", cost: "150k IDR класс" },
      { name: "Ubud Art Market", desc: "Сувениры, торговаться обязательно", mapQuery: "Ubud Traditional Art Market", tag: "рынок" },
      { name: "Saraswati Temple", desc: "Храм с прудом лотосов, бесплатно, 10 мин", mapQuery: "Pura Taman Saraswati Ubud", tag: "храм", cost: "бесплатно" },
      { name: "Goa Gajah (Elephant Cave)", desc: "Древний храм-пещера, 30 мин от Убуда", mapQuery: "Goa Gajah Ubud", tag: "храм", cost: "50k IDR" },
      { name: "Tirta Empul", desc: "Храм со священной водой, ритуал, саронг в аренду", mapQuery: "Tirta Empul Temple", tag: "храм", cost: "50k IDR" },
    ],
    cafes: [
      { name: "Milk & Madu", price: "$$", kitchen: "Бранч, пицца, семейное", desc: "Лучший бранч Убуда: all-day breakfast до 16:00. Пицца на лавовом камне 120–180k, eggs benedict 95k, burrito 110k. Всегда многолюдно.", mapQuery: "Milk and Madu Ubud", rating: 4.6, reviews: 3400 },
      { name: "Seniman Coffee Studio", price: "$$", kitchen: "Спешелти кофе, бранч", desc: "Культовая кофейня со своей обжаркой из Кинтамани. Латте 40–55k, сэндвичи 60–120k. Удобно работать с ноута, wifi.", mapQuery: "Seniman Coffee Studio Ubud", rating: 4.6, reviews: 2800 },
      { name: "Zest Ubud", price: "$$$", kitchen: "Веган, healthy, джунгли", desc: "Знаковое веганское место с бамбуковой архитектурой и панорамой джунглей. Jackfruit burger 120k, боулы 110–150k. Красиво на закате.", mapQuery: "Zest Ubud Penestanan", rating: 4.7, reviews: 2200 },
      { name: "Alchemy Bali", price: "$$", kitchen: "Raw vegan, салат-бар", desc: "Первое здоровое место Бали в Пенестанане. Салат-бар по весу ~130k, raw pizza 95k, мороженое без сахара. По утрам медитация на крыше.", mapQuery: "Alchemy Bali Ubud", rating: 4.4, reviews: 1800 },
      { name: "Sayuri Healing Food", price: "$$", kitchen: "Веган, healing food", desc: "Точка сбора веганов Убуда. Raw лазанья 110k, буррито 95k, знаменитые cheesecake без молочки. Тихий сад, йога рядом.", mapQuery: "Sayuri Healing Food Ubud", rating: 4.6, reviews: 1600 },
      { name: "Clear Café", price: "$$", kitchen: "Healthy, вегетарианская, local", desc: "Огромное место с подушками на полу и садом. Только балийские продукты, без алкоголя. Боулы 85–130k, смузи 55k. Разуваются на входе.", mapQuery: "Clear Cafe Ubud Hanoman", rating: 4.4, reviews: 4500 },
      { name: "Watercress Ubud", price: "$$", kitchen: "Австралийский бранч, кофе", desc: "Eggs benedict 95k, bowls 110k, флэт-уайт 45k. Живая музыка по средам/пятницам, много туристов с ноутами.", mapQuery: "Watercress Ubud", rating: 4.5, reviews: 2100 },
      { name: "Anomali Coffee", price: "$", kitchen: "Спешелти кофе, завтрак", desc: "Лучшая индонезийская обжарка — Бали, Ява, Суматра. Эспрессо 35k, латте 45k, завтраки 55–85k. На Jalan Raya.", mapQuery: "Anomali Coffee Ubud", rating: 4.5, reviews: 1900 },
      { name: "Warung Pulau Kelapa", price: "$", kitchen: "Балийская, warung", desc: "Традиционный варунг в старом балийском доме. Nasi kuning 35k, куриные сатэ — лучшие в Убуде, наси чампур 55k. Своя парковка.", mapQuery: "Warung Pulau Kelapa Ubud", rating: 4.5, reviews: 1400 },
      { name: "Warung Biah Biah", price: "$", kitchen: "Балийская, бюджет", desc: "Классика Jl. Goutama: 30–50k за основное блюдо. Nasi campur, tempe, лавар. Порции сытные, с утра до ночи.", mapQuery: "Warung Biah Biah Ubud", rating: 4.4, reviews: 3200 },
      { name: "Tucky Cafe", price: "$$", kitchen: "Средиземноморская, сэндвичи", desc: "Крошечное кафе на боковой улочке с авторскими сэндвичами 75–110k и выпечкой. Спешелти кофе. Лучше приходить к открытию.", mapQuery: "Tucky Cafe Ubud", rating: 4.7, reviews: 600 },
      { name: "Rusters Bali", price: "$$", kitchen: "Кофе, бранч, ресторан", desc: "Комплекс со своей обжаркой, пекарней и рестораном Sante. Кофе 40k, круассаны 35k, обеды 120–200k. Керамическая студия рядом.", mapQuery: "Rusters Bali Ubud", rating: 4.7, reviews: 800 },
      { name: "Hujan Locale", price: "$$$", kitchen: "Современная индонезийская", desc: "Ресторан шефа Will Meyrick — стрит-фуд Азии в упакованной подаче. Sharing menu 350–550k/чел. Стильный особняк, особый ужин.", mapQuery: "Hujan Locale Ubud", rating: 4.6, reviews: 1700 },
      { name: "Cafe Pomegranate", price: "$$", kitchen: "Интернациональная, рис. поля", desc: "Круглое кафе посреди рисовых полей Сайан — панорама 360°. Завтраки 75–110k, пиццы 120k. Идёшь 10 минут по тропе.", mapQuery: "Cafe Pomegranate Ubud", rating: 4.4, reviews: 2300 },
      { name: "Room4Dessert", price: "$$$", kitchen: "Десертное fine dining", desc: "Ресторан Will Goldfarb из Netflix Chef's Table. 9-курсовое дегустационное ~750k/чел: 5 закусок + 5 десертов. Бронь заранее.", mapQuery: "Room4Dessert Ubud", rating: 4.7, reviews: 900 },
    ],
    days: [
      { date: "9 июня", weekday: "вт", title: "Приезд в Убуд", items: [
        { time: "10:00", text: "Выезд из Семиньяка", emoji: "🛵" },
        { time: "12:00", text: "Заселение, обед в Clear Café" },
        { time: "14:00", text: "Работа", emoji: "💻" },
        { time: "18:30", text: "Campuhan Ridge Walk на закат" },
      ]},
      { date: "10 июня", weekday: "ср", items: [
        { time: "9:30", text: "Подъём, завтрак в Milk & Madu" },
        { time: "10:30", text: "Seniman Coffee — работа с ноута" },
        { time: "13:00", text: "Обед в Watercress" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "11 июня", weekday: "чт", items: [
        { time: "9:00", text: "Monkey Forest к открытию", emoji: "🐒" },
        { time: "10:30", text: "Завтрак в Alchemy" },
        { time: "12:00", text: "Jalan Hanoman / Jalan Dewi Sita — магазины" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "12 июня", weekday: "пт", items: [
        { time: "8:30", text: "Tegalalang Rice Terraces — до толпы", emoji: "🌾" },
        { time: "10:00", text: "Завтрак в Tis Café" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "13 июня", weekday: "сб", title: "Cretya + водопад", isWeekend: true, items: [
        { time: "9:30", text: "Завтрак в Hujan Locale" },
        { time: "11:00", text: "Tibumana Waterfall", emoji: "💦" },
        { time: "14:00", text: "Обед в Bebek Tepi Sawah" },
        { time: "15:30", text: "Cretya Ubud Day Club до заката", emoji: "🎯", highlight: true },
        { time: "20:00", text: "Ужин в Locavore / Naughty Nuri's" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "sidemen",
    name: "Сидемен",
    nights: 2,
    dates: "14–15 июня",
    summary: "Рисовые террасы без туристов, виды на Агунг, детокс",
    emoji: "🌾",
    color: "jungle",
    spots: [
      { name: "Sidemen Rice Terrace Walk", desc: "Прогулка по террасам, фермеры, коровы. Лучше утром", mapQuery: "Sidemen Rice Terrace Walk", tag: "природа", cost: "бесплатно" },
      { name: "Gembleng Waterfall", desc: "Каменные природные ванны-джакузи, 30 мин", mapQuery: "Gembleng Waterfall Sidemen", tag: "водопад", cost: "25k IDR" },
      { name: "Tukad Cepung Waterfall", desc: "Водопад в пещере со столбом света (полдень). 40 мин", mapQuery: "Tukad Cepung Waterfall", tag: "водопад", time: "12–14:00", cost: "20k IDR" },
      { name: "Iseh Viewpoint", desc: "Вид на Агунг", mapQuery: "Iseh Viewpoint Sidemen", tag: "смотровая" },
      { name: "Pura Bukit Tageh", desc: "Небольшой храм на холме, закат", mapQuery: "Pura Bukit Tageh", tag: "храм" },
      { name: "Tenun Pelangi", desc: "Традиционное ткачество эндек, купить шарф", mapQuery: "Tenun Pelangi Sidemen", tag: "ремесло" },
    ],
    cafes: [
      { name: "Sahaja by Samanvaya", price: "$$$", kitchen: "Fine dining, paddock-to-plate", desc: "Утончённый ресторан виллы Samanvaya с овощами из своего сада. Сет-меню ~400k, a la carte 150–250k. Открытая терраса, для особого ужина.", mapQuery: "Sahaja by Samanvaya Sidemen", rating: 4.9, reviews: 1900 },
      { name: "Wapa di Ume Sidemen", price: "$$$", kitchen: "Балийская, европейская", desc: "Ресторан 5★ курорта над рекой Унда. Элегантный ужин с видом на холмы, средний чек ~250k/чел. Завтраки открыты для всех.", mapQuery: "Wapa di Ume Sidemen", rating: 4.7, reviews: 600 },
      { name: "Joglo D'uma", price: "$$", kitchen: "Балийская, европейская", desc: "Лучший ресторан Сидемена с панорамой долины. Фирменный молочный поросёнок, ayam betutu 95k, pepes ikan 85k. Вечером хозяин играет на гитаре.", mapQuery: "Joglo D'uma Sidemen", rating: 4.6, reviews: 300 },
      { name: "Sleeping Gajah Kitchen", price: "$$", kitchen: "Local, international, healthy", desc: "Самое известное локальное место Сидемена. Панорама гор. Поке-боулы 75k, satay 60k, смузи-боулы 65k. Работает весь день.", mapQuery: "Sleeping Gajah Kitchen Sidemen", rating: 4.6, reviews: 400 },
      { name: "Lihat Sawah", price: "$", kitchen: "Балийская, западная", desc: "Между варунгом и рестораном: гирлянды, терраса над рис. полями. Mie goreng 45k, жареный кальмар 70k, банановые панкейки 40k.", mapQuery: "Lihat Sawah Sidemen", rating: 4.3, reviews: 260 },
      { name: "Warung D'Padi", price: "$", kitchen: "Балийская, warung", desc: "Простой семейный варунг у дороги. Наси горенг 30k, ми горенг 30k, свежие соки 20k. Туристы ценят за честные цены и вид на рис. поле.", mapQuery: "Warung D'Padi Sidemen", rating: 4.7, reviews: 220 },
      { name: "The Sidemen Restaurant", price: "$$", kitchen: "Интернациональная, европ.", desc: "Тихое место в деревне Telaga Tawang, лес вокруг. Завтраки 80–120k, пасты 110k. Вечером ужины при звёздах, бронь желательна.", mapQuery: "The Sidemen Restaurant", rating: 4.5, reviews: 250 },
      { name: "Sawah Indah Restaurant", price: "$", kitchen: "Балийская, западная", desc: "Ресторан при одноимённой вилле, открытый для всех. Pepes ikan 75k, nasi campur 55k, большой завтрак 60k. Вид на террасы с верхней части долины.", mapQuery: "Sawah Indah Villa Sidemen", rating: 4.3, reviews: 210 },
      { name: "Warung Classic Sidemen", price: "$", kitchen: "Балийская, pork ribs", desc: "Семейный варунг со знаменитыми свиными рёбрышками — раскупают к обеду. Ribs 85k, гриль-креветки 90k. Приходить до 14:00.", mapQuery: "Warung Classic Sidemen", rating: 4.5, reviews: 200 },
    ],
    days: [
      { date: "14 июня", weekday: "вс", title: "Переезд и отдых", isWeekend: true, items: [
        { time: "11:00", text: "Выезд Убуд → Сидемен (1:30)", emoji: "🛵" },
        { time: "13:00", text: "Заселение, обед" },
        { time: "16:00", text: "Прогулка по рисовым террасам" },
        { time: "19:00", text: "Ужин с видом на Агунг" },
      ]},
      { date: "15 июня", weekday: "пн", items: [
        { time: "9:30", text: "Подъём, завтрак в вилле / бассейн" },
        { time: "10:30", text: "Gembleng или Tukad Cepung", emoji: "💦" },
        { time: "13:00", text: "Обед" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "kintamani",
    name: "Кинтамани",
    nights: 5,
    dates: "16–20 июня",
    summary: "🌋 Батур (сб), горячие источники, лава, клубника",
    emoji: "🌋",
    color: "ocean",
    spots: [
      { name: "Mount Batur Sunrise Trek", desc: "Восхождение в 03:00, рассвет 1717 м. С гидом обязательно", mapQuery: "Mount Batur Sunrise Trek", tag: "восхождение", cost: "400–500k IDR с гидом" },
      { name: "Toya Devasya Hot Springs", desc: "Лучшие горячие источники, 4 бассейна + озеро", mapQuery: "Toya Devasya Hot Spring", tag: "спа", cost: "~200k IDR весь день" },
      { name: "Batur Natural Hot Spring", desc: "Бюджетнее Toya Devasya", mapQuery: "Batur Natural Hot Spring", tag: "спа", cost: "125k IDR" },
      { name: "Black Lava Field", desc: "Застывшая лава 1944 года, Pura Jati viewpoint", mapQuery: "Batur Black Lava Field Pura Jati", tag: "природа" },
      { name: "Pura Ulun Danu Batur", desc: "Храм на озере Батур", mapQuery: "Pura Ulun Danu Batur", tag: "храм", cost: "50k" },
      { name: "Kintamani Strawberry Farm", desc: "Собрать клубнику самому", mapQuery: "Kintamani Strawberry Farm", tag: "ферма" },
      { name: "Pancasari Strawberry Farm", desc: "Альтернатива, по дороге в Бедугул", mapQuery: "Pancasari Strawberry Farm", tag: "ферма" },
      { name: "Satria Agrowisata", desc: "Кофейная плантация, бесплатный тур + дегустация", mapQuery: "Satria Agrowisata Kintamani", tag: "кофе", cost: "бесплатно" },
      { name: "Bali Pulina", desc: "Премиум плантация, деревянная смотровая", mapQuery: "Bali Pulina", tag: "кофе", cost: "60k" },
      { name: "Pura Puncak Penulisan", desc: "Храм на вершине горы, вид с высоты", mapQuery: "Pura Puncak Penulisan", tag: "храм" },
      { name: "Trunyan Village", desc: "Деревня на лодке через озеро, необычные обряды", mapQuery: "Trunyan Village", tag: "этно" },
    ],
    cafes: [
      { name: "Montana del Cafe", price: "$$", kitchen: "Интернациональная, виды", desc: "Минималистичная архитектура и стеклянные стены с видом на Батур. Tiramisu 65k, eggs benedict 95k, пасты 120k. Самое фотогеничное место.", mapQuery: "Montana del Cafe Kintamani", rating: 4.5, reviews: 1500 },
      { name: "El Lago Batur", price: "$$", kitchen: "Японская, бранч, виды", desc: "Большое кафе с японским уклоном: рамен 95k, chicken katsu rice 110k, суши-сеты 140k. Открытые террасы с прямым видом на вулкан.", mapQuery: "El Lago Kintamani", rating: 4.5, reviews: 1200 },
      { name: "Kintamani Garden Cafe", price: "$$", kitchen: "Буфет, интернацион., виды", desc: "Большой ланч-буфет 150–180k с головой. Туристический формат, но виды на озеро и вулкан — лучшие. Средний вариант в туре.", mapQuery: "Kintamani Garden Cafe Batur", rating: 4.3, reviews: 2400 },
      { name: "Sila's Agrotourism", price: "$", kitchen: "Кофе-дегустация, luwak", desc: "Плантация с бесплатной дегустацией 10–12 сортов кофе и чая. Luwak coffee 60k (опция), обзорная на Батур. Короткая остановка.", mapQuery: "Sila's Agrotourism Kintamani", rating: 4.6, reviews: 1100 },
      { name: "Paperhills Cafe", price: "$$", kitchen: "Бранч, десерты, виды", desc: "Каскадная терраса над кратером в пастельной Palm Springs эстетике. Завтраки 70–110k, торты 55k, латте 45k. Отлично после восхождения.", mapQuery: "Paperhills Cafe Kintamani", rating: 4.6, reviews: 900 },
      { name: "Akasa Specialty Coffee", price: "$$", kitchen: "Спешелти кофе, бранч", desc: "Стеклянные павильоны прямо над обрывом к Батуру. Латте 45k, круассаны 40k, bowls и сэндвичи 85–120k. Открывается рано — идеально к восходу.", mapQuery: "Akasa Kintamani Coffee Bakery", rating: 4.5, reviews: 800 },
      { name: "Pahdi Specialty Coffee", price: "$$", kitchen: "Спешелти кофе, выпечка", desc: "Крупнейшая кофейня ЮВА — 4800 м². 4 своих обжарки из местного зерна, колдбрю 55–75k, завтраки 80–110k. Для фанатов кофе.", mapQuery: "Pahdi Specialty Coffee Kintamani", rating: 4.5, reviews: 700 },
      { name: "Black Lava Cafe", price: "$$", kitchen: "Бранч, бургеры, виды", desc: "Чёрный архитектурный бар прямо на лавовом поле. Бургеры 110k, пиццы 130k, коктейли 90k. На ужин драматично — солнце за вулкан.", mapQuery: "Black Lava Cafe Kintamani", rating: 4.4, reviews: 600 },
      { name: "The Amora Bali", price: "$$", kitchen: "Бранч, bowls, виды", desc: "Стеклянное кафе-капсула над обрывом. Smoothie bowls 75k, блины 60k, авокадо-тост 85k. Сюда за инстаграмом и завтраком перед/после вулкана.", mapQuery: "The Amora Bali Kintamani", rating: 4.4, reviews: 500 },
      { name: "Satu Satu Coffee", price: "$$", kitchen: "Спешелти кофе, бранч", desc: "Камерная кофейня с авторской обжаркой. Флэт-уайт 50k, авокадо-тост 85k, bowl 95k. Спокойный завтрак после Батура.", mapQuery: "Satu Satu Coffee Kintamani", rating: 4.6, reviews: 400 },
      { name: "Kaki Gunung", price: "$", kitchen: "Локальная, кофе, виды", desc: "Домашнее кафе-варунг с прямым видом на вулкан. Nasi goreng 45k, местный кофе 25k, банановый пирог 35k. Цены варунг, виды как у премиума.", mapQuery: "Kaki Gunung Kintamani", rating: 4.4, reviews: 300 },
      { name: "Tegukopi", price: "$", kitchen: "Локальная кофейня", desc: "Маленькая аутентичная кофейня с местным зерном. Кофе 20–40k, банановые чипсы, простые пирожные. Небольшая терраса, без туристической накрутки.", mapQuery: "Tegukopi Kintamani", rating: 4.3, reviews: 250 },
    ],
    days: [
      { date: "16 июня", weekday: "вт", items: [
        { time: "10:00", text: "Выезд Сидемен → Кинтамани (1:30)", emoji: "🛵" },
        { time: "11:30", text: "Заселение" },
        { time: "12:30", text: "Обед в Akasa с видом" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "17 июня", weekday: "ср", items: [
        { time: "9:30", text: "Завтрак в Hills Break" },
        { time: "10:30", text: "Toya Devasya Hot Springs (2 часа)", emoji: "♨️" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "18 июня", weekday: "чт", items: [
        { time: "9:30", text: "Подъём" },
        { time: "10:30", text: "Клубничная ферма — собрать клубнику", emoji: "🍓" },
        { time: "11:30", text: "Kintamani Coffee Plantation — дегустация" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "19 июня", weekday: "пт", title: "Подготовка к Батуру", items: [
        { time: "10:00", text: "Поздний подъём" },
        { time: "11:00", text: "Pura Ulun Danu Batur" },
        { time: "13:00", text: "Обед" },
        { time: "14:00", text: "Работа до 18:00", emoji: "💻" },
        { time: "19:00", text: "Плотный ужин" },
        { time: "20:00", text: "Лечь спать — ранний старт!" },
      ]},
      { date: "20 июня", weekday: "сб", title: "🌋 БАТУР + отдых", isWeekend: true, items: [
        { time: "02:00", text: "Подъём", emoji: "⏰" },
        { time: "03:00", text: "Старт восхождения на Батур 1717 м", emoji: "🌋", highlight: true },
        { time: "05:30", text: "Рассвет на вершине, завтрак из яиц с пара", highlight: true },
        { time: "07:00", text: "Спуск, обезьяны по пути" },
        { time: "10:00", text: "Возврат в отель, душ, спать" },
        { time: "14:00", text: "Поздний обед" },
        { time: "15:00", text: "Бассейн/спа, восстановление" },
        { time: "18:00", text: "Лёгкий ужин, ранний сон" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "amed",
    name: "Амед",
    nights: 5,
    dates: "21–25 июня",
    summary: "Дайвинг у корабля, массаж, йога, коворкинг, русская баня",
    emoji: "🌊",
    color: "ocean",
    spots: [
      { name: "USS Liberty Shipwreck (Tulamben)", desc: "Must-dive. 2 погружения, 15 мин от Амеда", mapQuery: "USAT Liberty Shipwreck Tulamben", tag: "дайв", time: "6:30 старт", cost: "1M IDR за 2 погружения" },
      { name: "Japanese Shipwreck Banyuning", desc: "Малый японский корабль, снорк от берега", mapQuery: "Japanese Shipwreck Banyuning Amed", tag: "снорк", cost: "бесплатно" },
      { name: "Jemeluk Bay Viewpoint", desc: "Смотровая, буквы AMED, закат", mapQuery: "Jemeluk Bay Viewpoint Amed", tag: "смотровая" },
      { name: "Blue Earth Village", desc: "Йога утром + коворкинг с видом на Агунг", mapQuery: "Blue Earth Village Amed", tag: "йога/коворкинг", cost: "150k класс" },
      { name: "Serenity Spa Amed", desc: "Массаж с видом", mapQuery: "Serenity Spa Amed", tag: "спа", cost: "250k/час" },
      { name: "Русская баня", desc: "Стеклянная стена, вид на Агунг. Уточнить адрес на месте", mapQuery: "Russian Banya Amed", tag: "баня" },
      { name: "Amed Salt Farms", desc: "Традиционная добыча соли из моря", mapQuery: "Amed Salt Farms", tag: "культура" },
      { name: "Jemeluk Beach Sunrise", desc: "Восход солнца над морем с видом на Агунг", mapQuery: "Jemeluk Beach Amed", tag: "пляж", time: "05:30" },
      { name: "Lipah Beach Sunset", desc: "Закат в сторону моря", mapQuery: "Lipah Beach Amed", tag: "пляж", time: "закат" },
      { name: "Freediving courses", desc: "Топ-место для фри-дайва на Бали", mapQuery: "Apneista Freediving Amed", tag: "фри-дайв" },
    ],
    cafes: [
      { name: "Warung Enak", price: "$", kitchen: "Индонезийская, европейская", desc: "Легенда Амеда. Наси горенг и сате 40–60k, пицца 70k. Цена/качество лучшие. #11 из 144 на TripAdvisor.", mapQuery: "Warung Enak Amed", rating: 4.6, reviews: 1701 },
      { name: "Sails Restaurant", price: "$$$", kitchen: "Европейская, fine dining", desc: "Премиум с видом на залив, греческая эстетика. Европейское меню, выдержанные вина. Для особого вечера.", mapQuery: "Sails Restaurant Amed", rating: 4.5, reviews: 1100 },
      { name: "Joli Best View Cafe", price: "$$", kitchen: "Индонез., европ., веган", desc: "На холме с панорамой залива Джемелук и Агунга. Лучший закат в Амеде. Большое вег/веган меню. Среднее блюдо 75–120k.", mapQuery: "Joli Best View Cafe Amed", rating: 4.7, reviews: 900 },
      { name: "Trattoria Amed", price: "$$", kitchen: "Итальянская", desc: "Лучшая итальянская в Амеде. Домашняя паста, неаполитанская пицца на тонком тесте, тыквенный равиоли, lobster linguine. Комплиментарные десерты.", mapQuery: "Trattoria Amed", rating: 4.7, reviews: 800 },
      { name: "Komang John's Cafe", price: "$$", kitchen: "Индонезийская, европ.", desc: "В Blue Moon Villas с видом на океан. Аутентичная балийская + европейская кухня. Стильно и релакс. Блюдо 90–150k.", mapQuery: "Komang John's Cafe Amed", rating: 4.6, reviews: 700 },
      { name: "Rimba Cafe", price: "$$", kitchen: "Healthy, веган, fusion", desc: "Бамбуковая архитектура, ботанический сад. Смузи-боулы, фалафели, кевиче. Йога, лайв-музыка. Must-try.", mapQuery: "Rimba Cafe Amed", rating: 4.7, reviews: 620 },
      { name: "Galanga", price: "$$", kitchen: "Тайско-индонез. фьюжн", desc: "Обед в бамбуковых хижинах в саду. Фьюжн + тайская + западная, много веган/вегет опций. Романтично, тихо.", mapQuery: "Galanga Restaurant Amed", rating: 4.7, reviews: 550 },
      { name: "Oneway Espresso", price: "$$", kitchen: "Кофейня, бранч, японский", desc: "Лучший кофе в Амеде. Smoothie bowls, авокадо-тосты, japanese-inspired блюда, выпечка. Латте ~40k, боул 80k.", mapQuery: "Oneway Espresso Amed", rating: 4.7, reviews: 508 },
      { name: "Aquaterrace", price: "$$", kitchen: "Японская, индонезийская", desc: "Вид на океан + японская кухня (катсу, темпура, суши) с индонезийскими акцентами. Альтернатива когда устал от наси горенга.", mapQuery: "Aquaterrace Amed", rating: 4.6, reviews: 500 },
      { name: "La Cocina Mexicana", price: "$$", kitchen: "Мексиканская", desc: "Самая аутентичная мексиканская на Бали вне туристических хабов. Домашние кукурузные тортильи, тако, гуакамоле. Taco Thursday — тако по 15k.", mapQuery: "La Cocina Mexicana Amed", rating: 4.8, reviews: 450 },
      { name: "Small Time Cooks", price: "$$", kitchen: "Бургеры, бао, фьюжн", desc: "Небольшое место с культовыми бургерами, бао-банами и банан-чай смузи. Быстро, вкусно, много возвращающихся. Бургер 95k.", mapQuery: "Small Time Cooks Amed", rating: 4.8, reviews: 400 },
      { name: "Warung Segara", price: "$", kitchen: "Рыба, морепродукты", desc: "Пляжный варунг на песке, свежая рыба прямо с лодок, готовят при вас. Одни из самых низких цен в Амеде и реально лучшая рыба.", mapQuery: "Warung Segara Amed", rating: 4.6, reviews: 350 },
      { name: "Good Stuff Cafe", price: "$$", kitchen: "Healthy, веган, кофейня", desc: "Eco-friendly, dog-friendly. Смузи-боулы, свежие салаты, gluten-free. При кафе эко-магазин с рефил-продуктами.", mapQuery: "Good Stuff Cafe Amed", rating: 4.7, reviews: 350 },
      { name: "See You Again Cafe", price: "$", kitchen: "Местная балийская", desc: "Локал-варунг на холме с видом на закат и Агунг. Хозяева — местная семья, душевно. Одна из самых вкусных местных кухонь.", mapQuery: "See You Again Cafe Amed", rating: 4.8, reviews: 250 },
    ],
    days: [
      { date: "21 июня", weekday: "вс", title: "Переезд после Батура", isWeekend: true, items: [
        { time: "10:00", text: "Подъём, долгий завтрак" },
        { time: "12:00", text: "Выезд Кинтамани → Амед (2:00)", emoji: "🛵" },
        { time: "14:00", text: "Приехали, заселение" },
        { time: "18:00", text: "Лёгкий ужин у моря" },
      ]},
      { date: "22 июня", weekday: "пн", items: [
        { time: "10:00", text: "Массаж (Serenity / Putri)", emoji: "💆" },
        { time: "12:00", text: "Завтрак в Warung Vienna" },
        { time: "14:00", text: "Работа", emoji: "💻" },
        { time: "18:30", text: "Закат на Jemeluk Bay Viewpoint" },
      ]},
      { date: "23 июня", weekday: "вт", items: [
        { time: "9:00", text: "Йога с видом на Агунг (Blue Earth)", emoji: "🧘" },
        { time: "10:30", text: "Завтрак там же" },
        { time: "14:00", text: "Работа из коворкинга", emoji: "💻" },
      ]},
      { date: "24 июня", weekday: "ср", title: "🤿 Дайвинг Liberty", items: [
        { time: "6:30", text: "Подъём" },
        { time: "7:00", text: "Выезд на дайв-центр" },
        { time: "8:00", text: "Два погружения на USS Liberty", emoji: "🤿", highlight: true },
        { time: "11:30", text: "Возврат, обед в Warung Ocean View" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "25 июня", weekday: "чт", title: "🧖 Русская баня", items: [
        { time: "10:00", text: "Подъём" },
        { time: "11:00", text: "Русская баня со стеклянной стеной", emoji: "🧖", highlight: true },
        { time: "13:00", text: "Обед в Warung Bamboo" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "lovina",
    name: "Ловина",
    nights: 3,
    dates: "26–28 июня",
    summary: "Дельфины, Aling-Aling с прыжками, планктон ночью",
    emoji: "🐬",
    color: "ocean",
    spots: [
      { name: "Dolphin boat tour", desc: "04:30 подъём, лодка, дельфины. Заказать накануне", mapQuery: "Lovina Dolphin Tour", tag: "лодка", time: "05:00", cost: "200k/чел" },
      { name: "Aling-Aling Waterfall", desc: "Must. Прыжки 5/10/15 м, горки, дикий 35-м водопад. Гид обязателен", mapQuery: "Aling-Aling Waterfall", tag: "водопад", cost: "125k с гидом" },
      { name: "Gitgit Waterfall", desc: "Классика, можно совместить с Aling-Aling", mapQuery: "Gitgit Waterfall", tag: "водопад", cost: "20k" },
      { name: "Banjar Hot Springs", desc: "Горячие источники в джунглях", mapQuery: "Banjar Hot Spring", tag: "спа", cost: "20k" },
      { name: "Brahmavihara-Arama", desc: "Буддистский монастырь, 30 мин от Ловины", mapQuery: "Brahmavihara Arama Buleleng", tag: "монастырь", cost: "бесплатно" },
      { name: "Singsing Waterfall", desc: "«Двойной» водопад ближе к Ловине", mapQuery: "Singsing Waterfall Lovina", tag: "водопад" },
      { name: "Kalibukbuk Beach", desc: "Чёрный песок, закат", mapQuery: "Kalibukbuk Beach Lovina", tag: "пляж", time: "закат" },
      { name: "Bioluminescent plankton tour", desc: "Лодка после 21:00, светящийся планктон. Сезон май-август ✓", mapQuery: "Lovina Bioluminescent Plankton Tour", tag: "лодка", time: "21:00+", cost: "~300k/чел" },
      { name: "Les Waterfall (Yeh Mampeh)", desc: "60-м водопад, по пути из Амеда", mapQuery: "Les Waterfall Bali", tag: "водопад" },
    ],
    cafes: [
      { name: "Spice Beach Club", price: "$$", kitchen: "Beach club, международ.", desc: "Пляжный бар на чёрном песке. Бургеры, rendang, пицца, лайв-музыка. Атмосферно на закате. Блюдо 100–180k.", mapQuery: "Spice Beach Club Lovina", rating: 4.3, reviews: 1251 },
      { name: "Buda Bakery & Resto", price: "$$", kitchen: "Пекарня, европ., бранч", desc: "Одно из лучших в северной Бали. Домашний хлеб, выпечка, eggs Benedict, смузи-боулы, лосось, pork burger, lemon cheesecake. Must для завтрака.", mapQuery: "Buda Bakery Lovina", rating: 4.7, reviews: 969 },
      { name: "Jasmine Kitchen", price: "$$", kitchen: "Тайская, кофе", desc: "15 лет в Ловине. Тайская кухня (с индонез. уклоном), специальный кофе, дружелюбный сервис. Том ям 75k, карри 85k.", mapQuery: "Jasmine Kitchen Lovina", rating: 4.5, reviews: 900 },
      { name: "Warung Jepun", price: "$", kitchen: "Индонезийская, балийская", desc: "Любимое туристами. Наси горенг, чикен сате, rendang, crispy duck, вегетарианские блюда. Бюджетно и аутентично.", mapQuery: "Warung Jepun Lovina", rating: 4.6, reviews: 800 },
      { name: "Global Village Kafe", price: "$$", kitchen: "Индонез., международ., веган", desc: "Некоммерческое кафе — все сотрудники с инвалидностью, прибыль идёт на благотворительность. Карри, пицца, паста, веган, домашние торты.", mapQuery: "Global Village Kafe Lovina", rating: 4.8, reviews: 700 },
      { name: "AKAR Cafe", price: "$$", kitchen: "Healthy, веган, бранч", desc: "Топ-место Ловины: smoothie bowls, avo toast, веган-рэпы, панкейки, кофе из балийских зёрен. Домашнее мороженое.", mapQuery: "AKAR Cafe Lovina", rating: 4.7, reviews: 611 },
      { name: "Bali Lovina Cafe", price: "$$", kitchen: "Международ., индонезийская", desc: "Один из самых известных ресторанов Ловины, международное меню, завтраки, вечерние блюда. Надёжный выбор.", mapQuery: "Bali Lovina Cafe Restaurant", rating: 4.5, reviews: 550 },
      { name: "The Damai", price: "$$$", kitchen: "Fine dining, farm-to-table", desc: "В холмах над Ловиной. Авторские tasting menu с балийскими акцентами, вид на океан. 30–50 EUR/чел. Fine dining опция.", mapQuery: "The Damai Lovina", rating: 4.8, reviews: 520 },
      { name: "Warung Dolphin", price: "$", kitchen: "Морепродукты, индонезийская", desc: "50м от пляжа. Seafood platter, гриль-креветки, лайв-музыка. Романтично, цена умеренная, ожидание бывает долгим.", mapQuery: "Warung Dolphin Lovina", rating: 4.5, reviews: 450 },
      { name: "Tropis Club", price: "$$", kitchen: "Европейская, бистро", desc: "Бистро у пляжа в Калибукбуке, европейская кухня, вечерняя атмосфера. Стабильная кухня, хороший сервис.", mapQuery: "Tropis Club Lovina", rating: 4.4, reviews: 380 },
      { name: "Lovinalife Cafe", price: "$$", kitchen: "Бранч, европ., healthy", desc: "Часть бутик-гестхауса в 5 мин от пляжа. Сад с муралами, растения. Healthy бранч, бургеры, свежие соки.", mapQuery: "Lovinalife Cafe Lovina", rating: 4.7, reviews: 320 },
      { name: "Jaring Cafe", price: "$$", kitchen: "Modern Indonesian fusion", desc: "Индустриальный стиль, модерн-фьюжн индонезийская кухня. Стильная атмосфера, отличие от типичных варунгов.", mapQuery: "Jaring Cafe Lovina", rating: 4.5, reviews: 280 },
    ],
    days: [
      { date: "26 июня", weekday: "пт", title: "Переезд из Амеда с остановками", items: [
        { time: "7:30", text: "Подъём, завтрак" },
        { time: "8:30", text: "Выезд Амед → Ловина (3:00)", emoji: "🛵" },
        { time: "", text: "Остановки: Tejakula, Les Waterfall 60м, Air Sanih" },
        { time: "13:00", text: "Приехали, заселение, обед" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "27 июня", weekday: "сб", title: "🎯 Aling-Aling + планктон", isWeekend: true, items: [
        { time: "9:00", text: "Завтрак" },
        { time: "10:00", text: "Aling-Aling Waterfall — прыжки 5/10/15 м", emoji: "🎯", highlight: true },
        { time: "13:00", text: "По пути — Gitgit Waterfall" },
        { time: "14:30", text: "Обед в Secret Garden" },
        { time: "18:30", text: "Закат на Kalibukbuk Beach" },
        { time: "20:00", text: "Ужин в Nia Bar" },
        { time: "21:30", text: "Bioluminescent plankton tour", emoji: "🌙", highlight: true },
      ]},
      { date: "28 июня", weekday: "вс", title: "🐬 Дельфины + Banjar", isWeekend: true, items: [
        { time: "4:30", text: "Подъём", emoji: "⏰" },
        { time: "5:00", text: "Лодка на дельфинов", emoji: "🐬", highlight: true },
        { time: "7:00", text: "Завтрак в The Damai / Buddha Banana" },
        { time: "10:00", text: "Banjar Hot Springs", emoji: "♨️" },
        { time: "12:00", text: "Brahmavihara-Arama монастырь" },
        { time: "13:30", text: "Обед, отдых" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "pemuteran",
    name: "Пемутеран",
    nights: 2,
    dates: "29–30 июня",
    summary: "Menjangan Island snorkeling, Biorock, черепахи, тихо",
    emoji: "🐢",
    color: "ocean",
    spots: [
      { name: "Menjangan Island snorkel/dive", desc: "Must. Лучший риф Бали, West Bali National Park. Лодка 8:00, 2–3 часа", mapQuery: "Menjangan Island Bali", tag: "снорк/дайв", cost: "400–600k/чел" },
      { name: "Biorock Pemuteran", desc: "Искусственный коралловый риф у берега, снорк бесплатно", mapQuery: "Biorock Pemuteran Bay", tag: "снорк", cost: "бесплатно" },
      { name: "Reef Seen Turtle Project", desc: "Центр спасения черепах, можно выпустить молодь", mapQuery: "Reef Seen Turtle Project Pemuteran", tag: "черепахи", cost: "~50k" },
      { name: "West Bali National Park", desc: "Джунгли, балийский скворец-эндемик, трекинг", mapQuery: "West Bali National Park", tag: "парк" },
      { name: "Pemuteran Beach sunset", desc: "Чёрный песок, тишина", mapQuery: "Pemuteran Beach", tag: "пляж", time: "закат" },
      { name: "Pulaki Temple", desc: "Храм с семьёй обезьян", mapQuery: "Pulaki Temple Bali", tag: "храм", cost: "бесплатно" },
      { name: "Jayaprana Tomb", desc: "Легендарная могила, смотровая", mapQuery: "Jayaprana Tomb Bali", tag: "смотровая" },
    ],
    cafes: [
      { name: "Bali Balance Cafe", price: "$$", kitchen: "Кофейня, веган, healthy", desc: "Говорят — лучший кофе на Бали. Скрыт в тропическом саду. Морковный торт, свежие соки, выпечка. Обязательное для завтрака.", mapQuery: "Bali Balance Cafe Pemuteran", rating: 4.7, reviews: 600 },
      { name: "Tirta Sari Restaurant", price: "$$$", kitchen: "Индонез., морепродукты, fine", desc: "У пляжа, бамбуковые лампы, романтичная атмосфера. Каждое блюдо — маленькое произведение искусства. Свежая рыба, балийская кухня.", mapQuery: "Tirta Sari Restaurant Pemuteran", rating: 4.6, reviews: 520 },
      { name: "La Casa Kita", price: "$$", kitchen: "Итальянская, пицца", desc: "Пицца из дровяной печи, La Casa Coco Tuna, Regina. Лайв-музыка, ухоженный газон. Холодное пиво + пицца.", mapQuery: "La Casa Kita Pemuteran", rating: 4.5, reviews: 480 },
      { name: "Frangipani Bar", price: "$$$", kitchen: "Международ., балийская", desc: "Двухэтажный open-plan, стильная подача, микс локального и западного. Элегантно, профессиональный сервис. Ужин с вином.", mapQuery: "Frangipani Bar Pemuteran", rating: 4.5, reviews: 420 },
      { name: "Taman Sari Beachfront", price: "$$$", kitchen: "Международ., балийская", desc: "Прямо на пляже Taman Sari Resort. International + местная кухня с видом на океан. Атмосферно — для особого случая.", mapQuery: "Taman Sari Bali Resort Pemuteran", rating: 4.5, reviews: 400 },
      { name: "Hungry Army Waroeng", price: "$", kitchen: "Индонез., морепродукты", desc: "Бюджетный варунг, известен BBQ из морепродуктов и авторскими шейками. Проводят кулинарные классы. Отличная цена/качество.", mapQuery: "Hungry Army Waroeng Pemuteran", rating: 4.6, reviews: 350 },
      { name: "Amertha Beachfront", price: "$$", kitchen: "Индонез., международ.", desc: "Пляжный ресторан с видом на волны, от завтрака до ужина. Релакс-атмосфера, хорошо для обеда у моря.", mapQuery: "Amertha Bali Beachfront Restaurant Pemuteran", rating: 4.4, reviews: 310 },
      { name: "The Sage Bali", price: "$$", kitchen: "Healthy, веган, вегет.", desc: "В центре Пемутерана. Яркие, ароматные блюда с акцентом на веган/вегет. Одно из немногих по-настоящему healthy.", mapQuery: "The Sage Bali Pemuteran", rating: 4.6, reviews: 280 },
      { name: "Warung Santai", price: "$", kitchen: "Балийская, семейная", desc: "Маленький семейный варунг, популярен у французов. Хозяйка Abu Made готовит свежие балийские блюда, сын играет на гитаре. Душевно.", mapQuery: "Warung Santai Pemuteran", rating: 4.7, reviews: 220 },
    ],
    days: [
      { date: "29 июня", weekday: "пн", items: [
        { time: "10:00", text: "Выезд Ловина → Пемутеран (1:15)", emoji: "🛵" },
        { time: "11:30", text: "Заселение" },
        { time: "12:00", text: "Biorock — снорк у берега", emoji: "🐠" },
        { time: "12:30", text: "Reef Seen Turtle Project", emoji: "🐢" },
        { time: "13:30", text: "Обед в Warung Kayu Manis" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "30 июня", weekday: "вт", title: "🤿 Menjangan Island", items: [
        { time: "7:00", text: "Подъём, лёгкий завтрак" },
        { time: "7:30", text: "На пирсе, лодка в West Bali NP" },
        { time: "8:00", text: "Snorkel / dive Menjangan", emoji: "🤿", highlight: true },
        { time: "12:30", text: "Возврат, обед в Seasalt" },
        { time: "14:00", text: "Работа", emoji: "💻" },
        { time: "19:00", text: "Ужин в The Kawi" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "munduk",
    name: "Мундук",
    nights: 3,
    dates: "1–3 июля",
    summary: "Водопады, озёра Буян/Тамблинган, храм Ulun Danu Beratan",
    emoji: "⛰",
    color: "jungle",
    spots: [
      { name: "Munduk Waterfall", desc: "Классика, лёгкий трек 15 мин", mapQuery: "Munduk Waterfall", tag: "водопад", cost: "20k" },
      { name: "Melanting Waterfall", desc: "Рядом с Мундук-водопадом, совмещённый трек", mapQuery: "Melanting Waterfall Munduk", tag: "водопад" },
      { name: "Red Coral Waterfall", desc: "Малоизвестный, фотогеничный", mapQuery: "Red Coral Waterfall Munduk", tag: "водопад" },
      { name: "Banyumala Twin Waterfall", desc: "Двойной водопад, одно из самых красивых мест Бали", mapQuery: "Banyumala Twin Waterfall", tag: "водопад", cost: "30k" },
      { name: "Twin Lakes Viewpoint (Wanagiri)", desc: "Панорама на Буян и Тамблинган", mapQuery: "Twin Lake Viewpoint Munduk", tag: "смотровая" },
      { name: "Wanagiri Hidden Hills", desc: "«Гнёзда» и качели для фото", mapQuery: "Wanagiri Hidden Hills", tag: "фото", cost: "50k" },
      { name: "Danau Buyan", desc: "Прогулка по берегу, каноэ", mapQuery: "Danau Buyan Bali", tag: "озеро" },
      { name: "Danau Tamblingan", desc: "Тихое священное озеро, каноэ", mapQuery: "Danau Tamblingan", tag: "озеро" },
      { name: "Pura Ulun Danu Beratan", desc: "Легендарный храм на озере. MUST на закате. 30 мин от Мундука", mapQuery: "Ulun Danu Beratan Temple", tag: "храм", time: "закат", cost: "75k" },
      { name: "Bali Handara Gate", desc: "Инстаграмные «ворота в небо». Очередь за фото 20 мин", mapQuery: "Bali Handara Gate", tag: "фото", cost: "50k" },
      { name: "Munduk Village Walk", desc: "Прогулка по деревне с гидом", mapQuery: "Munduk Village", tag: "прогулка" },
    ],
    cafes: [
      { name: "Warung Classic", price: "$", kitchen: "Балийская, warung с видом", desc: "Маленький варунг с потрясающим видом. Баклажан-баладо, жареная курица с балийскими специями. Цены низкие, порции честные.", mapQuery: "Warung Classic Munduk", rating: 4.7, reviews: 1073 },
      { name: "Ngiring Ngewedang", price: "$$", kitchen: "Балийская, кофе, панорама", desc: "Открытая терраса с видом на холмы. Лучший балийский кофе в Мундуке, капучино, Indo-блюда. Цены выше среднего, но вид того стоит.", mapQuery: "Ngiring Ngewedang Restaurant Munduk", rating: 4.3, reviews: 520 },
      { name: "Warung Made's", price: "$$", kitchen: "Балийская, международ.", desc: "С 1998 года, выросла из варунга в полноценный ресторан. Каждое блюдо с душой, честные цены, горные виды. Микс местного и западного.", mapQuery: "Warung Made's Munduk", rating: 4.9, reviews: 450 },
      { name: "Warung Heaven", price: "$$", kitchen: "Балийская, панорама", desc: "Легенда Мундука с захватывающей панорамой долины. Аутентичные балийские блюда, особенно хорош закат. Nasi campur ~65k, betutu 85k.", mapQuery: "Warung Heaven Munduk", rating: 4.8, reviews: 360 },
      { name: "Munduk Eco Cafe", price: "$", kitchen: "Балийская, кофе, эко", desc: "Домашнее кафе-варунг с прямым видом на вулкан. Свой кофе Lawak, домашняя еда. Одно из любимых у путешественников.", mapQuery: "Munduk Eco Cafe 2", rating: 4.6, reviews: 280 },
      { name: "Warung Kadirasa", price: "$", kitchen: "Балийская, индонезийская", desc: "Уникальное топовое место с отличным Nasi campur и домашними блюдами. Маленький, уютный. Высокий рейтинг.", mapQuery: "Warung Kadirasa Munduk", rating: 4.9, reviews: 220 },
      { name: "Golden Valley Breeze", price: "$", kitchen: "Балийская, warung", desc: "У водопада, тихое место с локальной кухней без наценки за локацию. Nasi goreng 40k, mie goreng 40k, свежие соки.", mapQuery: "Golden Valley Breeze Eco Cafe Munduk", rating: 4.6, reviews: 220 },
      { name: "Warung Kopi Bali Munduk", price: "$", kitchen: "Балийская, warung", desc: "Простая кухня высокогорья: pepes ikan, овощные блюда из своего огорода. Вид на гвоздичные и кофейные плантации.", mapQuery: "Warung Kopi Bali Restaurant Munduk", rating: 4.3, reviews: 210 },
      { name: "The Little Hill Terrace", price: "$$", kitchen: "Интернац., панорама", desc: "Ужин на холме с видом выше облаков. Романтические закаты, 360-градусный обзор гор. Pasta, burgers, балийское.", mapQuery: "The Little Hill Terrace Munduk", rating: 4.7, reviews: 210 },
      { name: "Warung D'Munduk", price: "$", kitchen: "Балийская, warung", desc: "Свежая домашняя еда, дёшево и вкусно. Одна из лучших панорам Мундука по отзывам туристов. Семейное место.", mapQuery: "Warung D'Munduk", rating: 4.7, reviews: 200 },
      { name: "The Botanist by Desa Eko", price: "$$$", kitchen: "Fine dining, farm-to-table", desc: "Ресторан на склоне среди деревьев, farm-to-table. Редкий в Мундуке формат уровня Убуда, ориентирован на туристов.", mapQuery: "The Botanist by Desa Eko Munduk", rating: 4.7, reviews: 200 },
      { name: "Don Biyu", price: "$$", kitchen: "Балийская, международ.", desc: "Гостевой дом с рестораном, панорама долины. Хорошие завтраки с фруктами и панкейками, местные блюда на ужин.", mapQuery: "Don Biyu Munduk", rating: 4.2, reviews: 145 },
    ],
    days: [
      { date: "1 июля", weekday: "ср", items: [
        { time: "9:00", text: "Выезд Пемутеран → Мундук (2:30)", emoji: "🛵" },
        { time: "11:30", text: "Заселение" },
        { time: "12:00", text: "Обед в Ngiring Ngewedang" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "2 июля", weekday: "чт", title: "Водопады", items: [
        { time: "9:30", text: "Завтрак в Don Biyu" },
        { time: "10:30", text: "Munduk + Melanting водопады (1.5 ч)", emoji: "💦" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "3 июля", weekday: "пт", title: "Озёра + храм на закат", items: [
        { time: "9:00", text: "Подъём" },
        { time: "10:00", text: "Twin Lakes Viewpoint" },
        { time: "10:30", text: "Wanagiri Hidden Hills (20 мин)" },
        { time: "11:30", text: "Banyumala Twin Waterfall", emoji: "💦" },
        { time: "14:00", text: "Работа", emoji: "💻" },
        { time: "18:00", text: "Pura Ulun Danu Beratan на закате", emoji: "🏯", highlight: true },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "jatiluwih",
    name: "Джатилувих",
    nights: 2,
    dates: "4–5 июля",
    summary: "UNESCO террасы, храм Батукару, тишина",
    emoji: "🌾",
    color: "jungle",
    spots: [
      { name: "Jatiluwih Rice Terraces", desc: "UNESCO. Трек-маршруты (красный/жёлтый/синий), 1–3 часа", mapQuery: "Jatiluwih Rice Terrace", tag: "природа", cost: "40k вход" },
      { name: "Pura Luhur Batukaru", desc: "Второй по значимости храм после Besakih, среди джунглей", mapQuery: "Pura Luhur Batukaru", tag: "храм", cost: "бесплатно, донат" },
      { name: "Leke Leke Waterfall", desc: "Спрятанный водопад в джунглях, 40 мин", mapQuery: "Leke Leke Waterfall", tag: "водопад", cost: "50k" },
      { name: "Yeh Hoo Waterfall", desc: "Каскад, мало людей", mapQuery: "Yeh Hoo Waterfall", tag: "водопад" },
      { name: "Gunung Batukaru trek", desc: "Восхождение 2276м, серьёзный трек (для энтузиастов)", mapQuery: "Mount Batukaru", tag: "трек" },
      { name: "Pupuan Rice Terraces", desc: "Ещё одни террасы, менее известные", mapQuery: "Pupuan Rice Terrace", tag: "природа" },
      { name: "Cycling по террасам", desc: "Велопрокат при Jatiluwih Visitor Center", mapQuery: "Jatiluwih Visitor Center", tag: "вело" },
    ],
    cafes: [
      { name: "Gong Jatiluwih", price: "$$", kitchen: "Балийская, интерн., панорама", desc: "Открытая bale-bengong архитектура с видом на террасы и три горы. Стейки 80–180k, Indo-кухня 40–100k.", mapQuery: "Gong Jatiluwih Restaurant", rating: 4.4, reviews: 650 },
      { name: "Jatiluwih Resto", price: "$$", kitchen: "Балийская, буфет", desc: "Популярный ресторан с буфетом и a la carte, вид на террасы. Удобно для группового обеда во время прогулки.", mapQuery: "Jatiluwih Resto", rating: 4.3, reviews: 450 },
      { name: "CataVaca Jatiluwih", price: "$$", kitchen: "Фьюжн индо-европейская", desc: "Фьюжн индонезийской и европейской кухни, хорошая презентация. В переулке, но вид на террасы и Insta-качели окупают поиск.", mapQuery: "CataVaca Jatiluwih", rating: 4.5, reviews: 320 },
      { name: "Batu Karu Kopi", price: "$$", kitchen: "Кофейня, бранч, healthy", desc: "Независимая кофейня и обжарка, 100% органическая арабика со своей фермы в 2 км. Бранч и выпечка, вид на Batukaru.", mapQuery: "Batu Karu Kopi Jatiluwih", rating: 4.8, reviews: 240 },
      { name: "Warung Dhea", price: "$$", kitchen: "Балийская, warung", desc: "Семейный warung с аутентичными балийскими блюдами и локальными ингредиентами. Nasi campur, gado-gado.", mapQuery: "Warung Dhea Jatiluwih", rating: 4.0, reviews: 220 },
      { name: "Bhuana Agung Villa", price: "$$", kitchen: "Балийская, международ.", desc: "Терраса прямо на краю с видом на рисовые террасы. Простая балийская и западная кухня, лучший spot для open-air ланча.", mapQuery: "Bhuana Agung Villa Restaurant Jatiluwih", rating: 4.3, reviews: 210 },
      { name: "Green Talas", price: "$", kitchen: "Балийская, домашняя", desc: "Тихое домашнее место с healthy-опциями. Простая свежая еда, индонезийские блюда и десерты. Спокойный обед.", mapQuery: "Green Talas Jatiluwih", rating: 4.4, reviews: 200 },
      { name: "Puri Jatiluwih", price: "$$", kitchen: "Балийская, международ.", desc: "Ресторан при гостевом комплексе с видом на террасы. Завтраки и обеды, смесь индонезийской и западной кухни.", mapQuery: "Puri Jatiluwih Restaurant", rating: 4.3, reviews: 200 },
    ],
    days: [
      { date: "4 июля", weekday: "сб", title: "🎯 Террасы + храм Батукару", isWeekend: true, items: [
        { time: "8:30", text: "Завтрак" },
        { time: "9:30", text: "Выезд Мундук → Джатилувих (1:30)", emoji: "🛵" },
        { time: "11:00", text: "Заселение" },
        { time: "11:30", text: "Jatiluwih Rice Terraces trekking", emoji: "🌾", highlight: true },
        { time: "13:30", text: "Обед в Gong Jatiluwih с панорамой" },
        { time: "15:00", text: "Pura Luhur Batukaru — храм в джунглях", emoji: "🏯", highlight: true },
        { time: "19:00", text: "Ужин" },
      ]},
      { date: "5 июля", weekday: "вс", title: "Водопад + отдых", isWeekend: true, items: [
        { time: "9:30", text: "Бассейн, завтрак" },
        { time: "11:00", text: "Leke Leke Waterfall (40 мин)", emoji: "💦" },
        { time: "13:00", text: "Обед в DHistory / Sang Giri" },
        { time: "14:00", text: "Отдых, прогулка по террасам" },
        { time: "18:00", text: "Закат на террасах" },
        { time: "20:00", text: "Ужин при свечах / костёр" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "seminyak",
    name: "Семиньяк",
    nights: 2,
    dates: "6–7 июля",
    summary: "Буфер перед вылетом, закаты, прощальный ужин",
    emoji: "🏖",
    color: "sunset",
    spots: [
      { name: "Potato Head Beach Club", desc: "Must. Закат, архитектура", mapQuery: "Potato Head Beach Club", tag: "beach club", time: "закат" },
      { name: "La Brisa Canggu", desc: "Beach club био-стиль", mapQuery: "La Brisa Canggu", tag: "beach club", time: "закат" },
      { name: "Seminyak Beach", desc: "Длинный пляж у Potato Head", mapQuery: "Seminyak Beach", tag: "пляж" },
      { name: "Seminyak Square", desc: "Шопинг, бренды", mapQuery: "Seminyak Square", tag: "шопинг" },
      { name: "Double Six Beach", desc: "Пляж с barlife", mapQuery: "Double Six Beach", tag: "пляж" },
      { name: "Tanah Lot", desc: "Храм на скале, 40 мин от Семиньяка, закат", mapQuery: "Tanah Lot", tag: "храм", time: "закат", cost: "60k" },
      { name: "Ku De Ta", desc: "Легендарный beach club", mapQuery: "Ku De Ta Seminyak", tag: "beach club" },
      { name: "Petitenget Beach", desc: "Тише, без толпы", mapQuery: "Petitenget Beach", tag: "пляж" },
    ],
    cafes: [
      { name: "Potato Head Beach Club", price: "$$$", kitchen: "Beach club, интернац.", desc: "Iconic beach club с ocean views. Барамунди bakar sambal dabu-dabu, sate babi kecap, burgers. Sunset DJ, бассейн.", mapQuery: "Potato Head Beach Club Seminyak", rating: 4.6, reviews: 20000 },
      { name: "Motel Mexicola", price: "$$$", kitchen: "Мексиканская, бар", desc: "Ярко-розовый мексиканский ресторан-бар, ручная тортилья Maseca. Тако, гуак, маргариты. Вечер переходит в вечеринку с латино.", mapQuery: "Motel Mexicola Seminyak", rating: 4.5, reviews: 4500 },
      { name: "La Favela", price: "$$$", kitchen: "Южноамериканская, клуб", desc: "Легендарный ресторан-клуб с 2013, jungle-фавела декор. Тако, spicy flautas, wagyu. После 22:00 — клуб до 3:00.", mapQuery: "La Favela Seminyak", rating: 4.3, reviews: 3200 },
      { name: "Merah Putih", price: "$$$", kitchen: "Fine dining Indonesian", desc: "Архитектурный ресторан с индонезийской кухней gourmet-уровня. Bak pao с суматранской говядиной, bebek goreng, ikan bakar. Mains 180k+.", mapQuery: "Merah Putih Restaurant Seminyak", rating: 4.5, reviews: 2900 },
      { name: "Sisterfields", price: "$$", kitchen: "Австралийский бранч", desc: "Мельбурнский all-day brunch — truffle scrambled eggs, chili cheese scrambled. Iconic место Семиньяка, очереди с открытия.", mapQuery: "Sisterfields Seminyak", rating: 4.5, reviews: 2800 },
      { name: "KYND Community", price: "$$", kitchen: "Vegan, healthy, бранч", desc: "Розовый iconic vegan-cafe на Petitenget. Smoothie bowls, vegan pancakes, tempeh bacon. До 16:00, Instagram-декор.", mapQuery: "Kynd Community Seminyak", rating: 4.5, reviews: 2400 },
      { name: "Biku", price: "$$", kitchen: "Интернац., high tea", desc: "150-летний Joglo, английский high tea, индонезийские блюда, салаты, veggie burgers, домашние пироги. Индийские и тайские акценты.", mapQuery: "Biku Seminyak", rating: 4.5, reviews: 2100 },
      { name: "Revolver Espresso", price: "$$", kitchen: "Спешелти кофе, бранч", desc: "Культовая кофейня с пряным интерьером и своей обжаркой. Breakfast burritos, huevos rancheros, smoothie bowls. Крепчайший кофе.", mapQuery: "Revolver Espresso Seminyak", rating: 4.5, reviews: 1800 },
      { name: "Sea Circus", price: "$$", kitchen: "Фьюжн, бранч, бар", desc: "Яркий интерьер с цирковыми мотивами. Тако, салаты, коктейли, smoothies, churros. All-day, хороший выбор веган-опций.", mapQuery: "Sea Circus Seminyak", rating: 4.4, reviews: 1800 },
      { name: "Mama San", price: "$$$", kitchen: "Modern Southeast Asian", desc: "Шеф Will Meyrick: тайская, вьетнамская, малайзийская, индонезийская, сингапурская. Колониальные интерьеры, one of Bali's reference points.", mapQuery: "Mama San Bali Seminyak", rating: 4.5, reviews: 1500 },
      { name: "Cafe Organic", price: "$$", kitchen: "Органика, veg, healthy", desc: "Пионер healthy-сцены Бали. Холодные соки, авокадо-тосты, superfood smoothies. Переработанное дерево и растения.", mapQuery: "Cafe Organic Seminyak", rating: 4.4, reviews: 1500 },
      { name: "Livingstone Cafe", price: "$$", kitchen: "Бранч, выпечка", desc: "All-day breakfast, свежая выпечка, круассаны, breakfast bagels, smoothie bowls. Staple бранч-сцены Семиньяка.", mapQuery: "Livingstone Cafe Bakery Seminyak", rating: 4.4, reviews: 1400 },
      { name: "Pison Coffee", price: "$$", kitchen: "Спешелти кофе, бранч", desc: "Индустриально-тропический cafe с кофе из всей Индонезии. All-day brunch: fluffy pancakes, eggs benedict, lobster toast.", mapQuery: "Pison Coffee Petitenget", rating: 4.6, reviews: 1200 },
      { name: "Monsieur Spoon", price: "$$", kitchen: "Французская пекарня", desc: "Парижская пекарня с 2012. Круассаны, pain au chocolat, домашний хлеб, sandwiches, quiche. Хороший кофе, ланч-сеты.", mapQuery: "Monsieur Spoon Petitenget", rating: 4.3, reviews: 900 },
      { name: "Da Maria", price: "$$$", kitchen: "Итальянская, пицца", desc: "Неаполитанские пиццы 24-часового брожения, паста. Интерьер от римских архитекторов. Fine dining vibe без снобизма.", mapQuery: "Da Maria Seminyak", rating: 4.3, reviews: 774 },
      { name: "Nalu Bowls", price: "$$", kitchen: "Smoothie bowls, healthy", desc: "Легендарные smoothie bowls Бали. Acai, pitaya, Tropical bowls, полезный завтрак. Простой формат, большие порции.", mapQuery: "Nalu Bowls Seminyak", rating: 4.4, reviews: 560 },
    ],
    days: [
      { date: "6 июля", weekday: "пн", items: [
        { time: "10:00", text: "Выезд Джатилувих → Семиньяк (2:00)", emoji: "🛵" },
        { time: "12:00", text: "Заселение" },
        { time: "13:00", text: "Обед в Sisterfields" },
        { time: "14:00", text: "Работа", emoji: "💻" },
        { time: "20:00", text: "Ужин в La Lucciola" },
      ]},
      { date: "7 июля", weekday: "вт", title: "Прощание с Бали", items: [
        { time: "9:30", text: "Бассейн / пляж" },
        { time: "11:00", text: "Шопинг на Seminyak Square" },
        { time: "14:00", text: "Работа (последний день)", emoji: "💻" },
        { time: "18:00", text: "Закат в Potato Head / La Brisa", emoji: "🌅", highlight: true },
        { time: "20:30", text: "Прощальный ужин: Merah Putih / Sarong / Mama San" },
      ]},
    ],
  },
];

export function getPlace(slug: string): Place | undefined {
  return PLACES.find((p) => p.slug === slug);
}
