import type { Place } from "./types";

export const TRIP_META = {
  start: "9 июня 2026",
  end: "8 июля 2026",
  totalNights: 29,
  travelers: 2,
  workingHours: "с 14:00 до ночи по будням",
};

// Главные точки маршрута (для карты)
export const ROUTE_POINTS = [
  "Seminyak, Bali, Indonesia",
  "Ubud, Bali, Indonesia",
  "Sidemen, Karangasem, Bali, Indonesia",
  "Kintamani, Bangli, Bali, Indonesia",
  "Amed, Karangasem, Bali, Indonesia",
  "Lovina Beach, Buleleng, Bali, Indonesia",
  "Pemuteran, Buleleng, Bali, Indonesia",
  "Munduk, Buleleng, Bali, Indonesia",
  "Jatiluwih, Tabanan, Bali, Indonesia",
  "Seminyak, Bali, Indonesia",
];

// Координаты каждой локации (lat, lon) — для карты в app
export const PLACE_COORDS: Record<string, { lat: number; lon: number }> = {
  seminyak: { lat: -8.6898, lon: 115.1711 },
  ubud: { lat: -8.5069, lon: 115.2625 },
  sidemen: { lat: -8.4556, lon: 115.4492 },
  kintamani: { lat: -8.2778, lon: 115.3525 },
  amed: { lat: -8.3400, lon: 115.6864 },
  lovina: { lat: -8.1583, lon: 115.0283 },
  pemuteran: { lat: -8.1425, lon: 114.6517 },
  munduk: { lat: -8.2628, lon: 115.0681 },
  jatiluwih: { lat: -8.3706, lon: 115.1367 },
};

// Bounding box Бали (для OSM embed)
export const BALI_BBOX = "114.40,-8.87,115.72,-8.03";

export const PLACES: Place[] = [
  // =========================================================
  {
    slug: "ubud",
    name: "Убуд",
    nights: 5,
    dates: "9–13 июня",
    summary: "Лес обезьян, рисовые террасы, Cretya, водопады, йога",
    emoji: "🌿",
    color: "jungle",
    spots: [
      { name: "Monkey Forest", desc: "Лес обезьян. Открытие 9:00, к 10 народ. Прячь очки и телефоны", mapQuery: "Sacred Monkey Forest Sanctuary Ubud", tag: "парк", time: "утро", cost: "80k IDR" },
      { name: "Tegalalang Rice Terraces", desc: "Классика рисовых террас. К 8:00 без толпы", mapQuery: "Tegalalang Rice Terrace", tag: "природа", time: "утро", cost: "25k IDR" },
      { name: "Campuhan Ridge Walk", desc: "Лёгкий трек по холму, 1 час, бесплатно", mapQuery: "Campuhan Ridge Walk Ubud", tag: "прогулка", time: "утро/закат" },
      { name: "Tibumana Waterfall", desc: "Один красивый водопад, озерцо для купания, 45 мин от Убуда", mapQuery: "Tibumana Waterfall", tag: "водопад", cost: "20k IDR" },
      { name: "Tegenungan Waterfall", desc: "Ближе к Убуду, более туристический", mapQuery: "Tegenungan Waterfall", tag: "водопад", cost: "20k IDR" },
      { name: "Cretya Ubud Day Club", desc: "Бассейн, коктейли, идеально на закат", mapQuery: "Cretya Ubud", tag: "day club", time: "с обеда до заката", cost: "300k+ minimum spend" },
      { name: "Yoga Barn", desc: "Культовая йога-студия, классы с 7:30", mapQuery: "The Yoga Barn Ubud", tag: "йога", cost: "150k IDR класс" },
      { name: "Ubud Art Market", desc: "Сувениры, торговаться обязательно", mapQuery: "Ubud Traditional Art Market", tag: "рынок" },
      { name: "Saraswati Temple", desc: "Храм с прудом лотосов, бесплатно, 10 мин", mapQuery: "Pura Taman Saraswati Ubud", tag: "храм", cost: "бесплатно" },
      { name: "Goa Gajah (Elephant Cave)", desc: "Древний храм-пещера, 30 мин от Убуда", mapQuery: "Goa Gajah Ubud", tag: "храм", cost: "50k IDR" },
      { name: "Tirta Empul", desc: "Храм со священной водой, ритуал, саронг в аренду", mapQuery: "Tirta Empul Temple", tag: "храм", cost: "50k IDR" },
    ],
    cafes: [
      { name: "Milk & Madu", price: "$$", kitchen: "Австралийский бранч", desc: "Классика Убуда. Eggs benedict 95k, пицца 120–180k, burrito 110k. Будничный сет (блюдо+кофе+сок) 110k в 7–10 утра Пн–Пт.", mapQuery: "Milk and Madu Ubud", rating: 4.6, reviews: 3400 },
      { name: "Watercress Ubud", price: "$$", kitchen: "Бранч-кафе", desc: "Benny Brunch (eggs benedict + сок + кофе + чиа-пудинг) ~150k. Boosted bowls, сэндвичи, супы. Wifi норм.", mapQuery: "Watercress Ubud", rating: 4.6, reviews: 2800 },
      { name: "Monsieur Spoon Ubud", price: "$", kitchen: "Французская пекарня", desc: "Лучшие круассаны на Бали. Almond croissant и pain au chocolat 52k, quiche lorraine 79k, багеты. Тихий сад — идеально для завтрака.", mapQuery: "Monsieur Spoon Ubud", rating: 4.5, reviews: 1900 },
      { name: "Umah Pizza", price: "$", kitchen: "Итальянская пиццерия", desc: "Дровяная пицца по честной цене. Пиццы 60–100k, пасты 55–95k. Самое бюджетное аутентичное итальянское в Убуде.", mapQuery: "Umah Pizza Ubud", rating: 4.7, reviews: 1500 },
      { name: "Pizza Bagus", price: "$$", kitchen: "Итальянская", desc: "Убудская классика с 1996. Стандартные пиццы и пасты по адекватным ценам 80–140k. Без сюрпризов — просто надёжно и вкусно.", mapQuery: "Pizza Bagus Ubud", rating: 4.4, reviews: 1700 },
      { name: "L'Osteria Ubud", price: "$$", kitchen: "Региональная итальянская", desc: "Хэнд-мейд пицца из дровяной печи в уютном деревянном зале. Пиццы 80–150k, пасты 75–140k. Как в маленькой итальянской таверне.", mapQuery: "L'Osteria Ubud", rating: 4.6, reviews: 900 },
      { name: "Alchemy Bali", price: "$$", kitchen: "Raw vegan, салат-бар", desc: "Салат-бар по весу ~90–130k, raw pizza, smoothie bowls, raw-десерты. Большой светлый зал.", mapQuery: "Alchemy Bali Ubud", rating: 4.5, reviews: 1800 },
      { name: "Sayuri Healing Food", price: "$$", kitchen: "Raw vegan", desc: "Культовое вегетарианское кафе в центре. Raw лазанья 110k, буррито 95k, cheesecake без молочки. Отличный wifi для работы.", mapQuery: "Sayuri Healing Food Ubud", rating: 4.6, reviews: 2300 },
      { name: "Zest Ubud", price: "$$", kitchen: "Plant-based, джунгли", desc: "Джунгли-оазис на холме. Smoothie bowls, суши, пасты — всё растительное. Красивейшая терраса. Завтраки 80–120k, основное 120–180k.", mapQuery: "Zest Ubud Penestanan", rating: 4.7, reviews: 2500 },
      { name: "Melali Ubud", price: "$", kitchen: "Кафе весь день", desc: "Завтраки весь день за 55–90k, подальше от туристической суеты. Тихая веранда, приличный кофе, тосты, боулы.", mapQuery: "Melali Ubud", rating: 4.6, reviews: 700 },
      { name: "Yellow Flower Cafe", price: "$", kitchen: "Органик завтраки", desc: "Скрытый органик-кафе с wifi. Healthy завтраки 59–79k, вегетарианские боулы. Вид на джунгли, мало туристов.", mapQuery: "Yellow Flower Cafe Ubud", rating: 4.7, reviews: 600 },
      { name: "Fair Warung Bale", price: "$", kitchen: "Легендарный warung", desc: "Must-try local. Прибыль идёт в клинику. Наси чампур 35k, соки 25k, куриные сатэ. Чисто и душевно.", mapQuery: "Fair Warung Bale Ubud", rating: 4.8, reviews: 3100 },
      { name: "Hujan Locale", price: "$$$", kitchen: "Современная индонезийская", desc: "Особый ужин. Шеф Will Meyrick — стрит-фуд Азии в упакованной подаче. Sharing menu 350–550k/чел. Бронь.", mapQuery: "Hujan Locale Ubud", rating: 4.6, reviews: 1700 },
    ],
    workspaces: [
      { name: "Outpost Penestanan", type: "Коворкинг", equipment: "24/7, AC, эргономичные кресла, кухня, розетки, переговорки", desc: "Крупнейший коворкинг Убуда, 24/7. 68 рабочих мест, события по средам/пятницам. Дневной пропуск 150–180k.", mapQuery: "Outpost Ubud Penestanan", rating: 4.7, reviews: 450, price: "150–180k/день" },
      { name: "Ubud.Space Coworking", type: "Коворкинг", equipment: "24/7, AC, розетки у каждого стола, тихие зоны", desc: "В центре Убуда, работает круглосуточно. Быстрый стабильный wifi, кофе. Идеален для работы допоздна.", mapQuery: "Ubud Space Coworking Coffee", rating: 4.6, reviews: 220, price: "120k/день" },
      { name: "Titi Batu Ubud Club", type: "Кафе-коворкинг", equipment: "Коворкинг + бассейн, AC, розетки, еда", desc: "Клуб со спа, бассейном, коворкингом. Работает 7:00–22:00. Тихо среди рисовых полей, отличный wifi.", mapQuery: "Titi Batu Ubud Club", rating: 4.5, reviews: 600, price: "150k/день (с депозитом на еду)" },
      { name: "Seniman Coffee Studio", type: "Кафе с wifi", equipment: "Быстрый wifi, розетки, спешелти кофе", desc: "Легендарная кофейня, 7:30–22:00. Стабильный wifi, много розеток. Идеально для работы до 22:00.", mapQuery: "Seniman Coffee Studio Ubud", rating: 4.6, reviews: 2800, price: "80–150k средний чек" },
    ],
    days: [
      { date: "9 июня", weekday: "вт", title: "Приезд в Убуд", items: [
        { time: "10:00", text: "Выезд из Семиньяка", emoji: "🛵" },
        { time: "12:00", text: "Заселение, обед в Clear Café" },
        { time: "14:00", text: "Работа", emoji: "💻" },
        { time: "18:30", text: "Campuhan Ridge Walk на закат" },
      ]},
      { date: "10 июня", weekday: "ср", items: [
        { time: "9:30", text: "Подъём, завтрак в Milk & Madu" },
        { time: "10:30", text: "Seniman Coffee — работа с ноута" },
        { time: "13:00", text: "Обед в Watercress" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "11 июня", weekday: "чт", items: [
        { time: "9:00", text: "Monkey Forest к открытию", emoji: "🐒" },
        { time: "10:30", text: "Завтрак в Alchemy" },
        { time: "12:00", text: "Jalan Hanoman / Jalan Dewi Sita — магазины" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "12 июня", weekday: "пт", items: [
        { time: "8:30", text: "Tegalalang Rice Terraces — до толпы", emoji: "🌾" },
        { time: "10:00", text: "Завтрак в Tis Café" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "13 июня", weekday: "сб", title: "Cretya + водопад", isWeekend: true, items: [
        { time: "9:30", text: "Завтрак в Hujan Locale" },
        { time: "11:00", text: "Tibumana Waterfall", emoji: "💦" },
        { time: "14:00", text: "Обед в Bebek Tepi Sawah" },
        { time: "15:30", text: "Cretya Ubud Day Club до заката", emoji: "🎯", highlight: true },
        { time: "20:00", text: "Ужин в Locavore / Naughty Nuri's" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "sidemen",
    name: "Сидемен",
    nights: 2,
    dates: "14–15 июня",
    summary: "Рисовые террасы без туристов, виды на Агунг, детокс",
    emoji: "🌾",
    color: "jungle",
    spots: [
      { name: "Sidemen Rice Terrace Walk", desc: "Прогулка по террасам, фермеры, коровы. Лучше утром", mapQuery: "Sidemen Rice Terrace Walk", tag: "природа", cost: "бесплатно" },
      { name: "Gembleng Waterfall", desc: "Каменные природные ванны-джакузи, 30 мин", mapQuery: "Gembleng Waterfall Sidemen", tag: "водопад", cost: "25k IDR" },
      { name: "Tukad Cepung Waterfall", desc: "Водопад в пещере со столбом света (полдень). 40 мин", mapQuery: "Tukad Cepung Waterfall", tag: "водопад", time: "12–14:00", cost: "20k IDR" },
      { name: "Iseh Viewpoint", desc: "Вид на Агунг", mapQuery: "Iseh Viewpoint Sidemen", tag: "смотровая" },
      { name: "Pura Bukit Tageh", desc: "Небольшой храм на холме, закат", mapQuery: "Pura Bukit Tageh", tag: "храм" },
      { name: "Tenun Pelangi", desc: "Традиционное ткачество эндек, купить шарф", mapQuery: "Tenun Pelangi Sidemen", tag: "ремесло" },
    ],
    cafes: [
      { name: "Sleeping Gajah Kitchen", price: "$$", kitchen: "Азия/Запад фьюжн", desc: "Ключевое место для экспатов Сидемена. Домашние завтраки с беконом, burgers, пасты, азиатские блюда. Расслабленная веранда в долине.", mapQuery: "Sleeping Gajah Sidemen", rating: 4.7, reviews: 400 },
      { name: "Asri Dining by Samanvaya", price: "$$", kitchen: "Интернац., бранч", desc: "Завтрак с видом на рисовые террасы: омлет с беконом, свежие соки. Обед — пасты, салаты, curry. Чек 120–180k.", mapQuery: "Samanvaya Bali Sidemen", rating: 4.7, reviews: 350 },
      { name: "Wapa di Ume Sidemen", price: "$$", kitchen: "Западная/балийская", desc: "Открытая терраса над рекой Унда. Завтраки, сэндвичи, пасты. Tripadvisor Travelers' Choice. Чек 150–220k.", mapQuery: "Wapa di Ume Sidemen", rating: 4.8, reviews: 500 },
      { name: "Joglo d'Uma", price: "$", kitchen: "Балийская/интернац.", desc: "Простая терраса с видом. Наси горенг, пасты, сэндвичи, свежие соки. Завтрак 50–80k. Повседневно и дёшево.", mapQuery: "Joglo d'Uma Sidemen", rating: 4.6, reviews: 250 },
      { name: "Warung Uma Anyar", price: "$", kitchen: "Балийская легенда", desc: "Must-try warung долины — nasi campur bali с аутентичными гарнирами. Блюдо 35–60k, семейная кухня.", mapQuery: "Warung Uma Anyar Sidemen", rating: 4.7, reviews: 300 },
      { name: "The Sidemen Restaurant", price: "$$$", kitchen: "Фьюжн fine dining", desc: "Особый ужин — единственный fine dining в локации. Ужин ~350k/чел, рисовые террасы и лес вокруг.", mapQuery: "The Sidemen Restaurant", rating: 4.7, reviews: 280 },
    ],
    workspaces: [
      { name: "Samanvaya Citrus & Vine Cafe", type: "Кафе с wifi", equipment: "Wifi, розетки, кофе, пекарня", desc: "Кафе-бейкери у дороги при отеле-ретрите. Днём и вечером до ~21:00. Для работы после 21 — из своей виллы.", mapQuery: "Samanvaya Bali Sidemen", rating: 4.7, reviews: 250, price: "80–150k средний чек" },
      { name: "Joglo D'Uma", type: "Кафе с wifi", equipment: "Wifi, розетки у части столов", desc: "Ресторан в традиционном жоглоу с wifi. Работает до ~21:00. Для работы до ночи — из отеля/виллы с проверенным wifi.", mapQuery: "Joglo D'Uma Sidemen", rating: 4.6, reviews: 350, price: "100–180k чек" },
    ],
    workNote: "В Сидемене нет коворкингов. После 21:00 работа только из виллы — выбирай заранее жильё с надёжным wifi.",
    days: [
      { date: "14 июня", weekday: "вс", title: "Переезд и отдых", isWeekend: true, items: [
        { time: "11:00", text: "Выезд Убуд → Сидемен (1:30)", emoji: "🛵" },
        { time: "13:00", text: "Заселение, обед" },
        { time: "16:00", text: "Прогулка по рисовым террасам" },
        { time: "19:00", text: "Ужин с видом на Агунг" },
      ]},
      { date: "15 июня", weekday: "пн", items: [
        { time: "9:30", text: "Подъём, завтрак в вилле / бассейн" },
        { time: "10:30", text: "Gembleng или Tukad Cepung", emoji: "💦" },
        { time: "13:00", text: "Обед" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "kintamani",
    name: "Кинтамани",
    nights: 5,
    dates: "16–20 июня",
    summary: "🌋 Батур (сб), горячие источники, лава, клубника",
    emoji: "🌋",
    color: "ocean",
    spots: [
      { name: "Mount Batur Sunrise Trek", desc: "Восхождение в 03:00, рассвет 1717 м. С гидом обязательно", mapQuery: "Mount Batur Sunrise Trek", tag: "восхождение", cost: "400–500k IDR с гидом" },
      { name: "Toya Devasya Hot Springs", desc: "Лучшие горячие источники, 4 бассейна + озеро", mapQuery: "Toya Devasya Hot Spring", tag: "спа", cost: "~200k IDR весь день" },
      { name: "Batur Natural Hot Spring", desc: "Бюджетнее Toya Devasya", mapQuery: "Batur Natural Hot Spring", tag: "спа", cost: "125k IDR" },
      { name: "Black Lava Field", desc: "Застывшая лава 1944 года, Pura Jati viewpoint", mapQuery: "Batur Black Lava Field Pura Jati", tag: "природа" },
      { name: "Pura Ulun Danu Batur", desc: "Храм на озере Батур", mapQuery: "Pura Ulun Danu Batur", tag: "храм", cost: "50k" },
      { name: "Kintamani Strawberry Farm", desc: "Собрать клубнику самому", mapQuery: "Kintamani Strawberry Farm", tag: "ферма" },
      { name: "Pancasari Strawberry Farm", desc: "Альтернатива, по дороге в Бедугул", mapQuery: "Pancasari Strawberry Farm", tag: "ферма" },
      { name: "Satria Agrowisata", desc: "Кофейная плантация, бесплатный тур + дегустация", mapQuery: "Satria Agrowisata Kintamani", tag: "кофе", cost: "бесплатно" },
      { name: "Bali Pulina", desc: "Премиум плантация, деревянная смотровая", mapQuery: "Bali Pulina", tag: "кофе", cost: "60k" },
      { name: "Pura Puncak Penulisan", desc: "Храм на вершине горы, вид с высоты", mapQuery: "Pura Puncak Penulisan", tag: "храм" },
      { name: "Trunyan Village", desc: "Деревня на лодке через озеро, необычные обряды", mapQuery: "Trunyan Village", tag: "этно" },
    ],
    cafes: [
      { name: "Montana Del Cafe", price: "$$", kitchen: "Западный завтрак", desc: "Минималистичный cafe с панорамой на Батур. Тосты, бейглы, круассаны, smoothie bowls, pancakes. Долгий завтрак 100–160k.", mapQuery: "Montana Del Cafe Kintamani", rating: 4.5, reviews: 1400 },
      { name: "Paperhills Kintamani", price: "$$", kitchen: "Бранч-кафе", desc: "Открывается в 5:30 — для встречи восхода. Завтраки, обеды, бургеры, паста. Панорама озера Батур. Чек 100–180k.", mapQuery: "Paperhills Kintamani", rating: 4.5, reviews: 900 },
      { name: "AKSAKA Kintamani", price: "$$", kitchen: "Спешелти кофе, кафе", desc: "Обжаривают свой кофе из Кинтамани. Знаменитая дорожка над кратером. Смузи, завтраки, сэндвичи, десерты. Чек 80–150k.", mapQuery: "AKSAKA Kintamani", rating: 4.6, reviews: 1800 },
      { name: "Ritatkala Cafe", price: "$$", kitchen: "Кафе с видом", desc: "Стеклянная стена на Батур. Batur Tea с корицей, завтраки, пиццы, пасты. Без минимального заказа — можно зайти на кофе. 80–150k.", mapQuery: "Ritatkala Cafe Kintamani", rating: 4.5, reviews: 1200 },
      { name: "Kintamani Garden Cafe", price: "$$", kitchen: "Буфет, интернац., виды", desc: "Большой ланч-буфет 150–180k с головой. Туристический формат, но виды на озеро и вулкан лучшие.", mapQuery: "Kintamani Garden Cafe Batur", rating: 4.3, reviews: 2400 },
      { name: "The Amora Bali", price: "$$", kitchen: "Интернац., бранч", desc: "Ресторан отеля на гребне кальдеры. Завтраки, пасты, салаты, пиццы. Горный бриз, чек 100–180k.", mapQuery: "The Amora Bali Kintamani", rating: 4.5, reviews: 600 },
      { name: "Eco Bike Coffee", price: "$", kitchen: "Спешелти кофе", desc: "Farm-to-cup: кофе делают на месте от сбора до обжарки. Простое меню, тосты и выпечка. Кофе 30–50k, блюдо 60–90k.", mapQuery: "Eco Bike Coffee Kintamani", rating: 4.7, reviews: 400 },
      { name: "Sila's Agrotourism", price: "$", kitchen: "Кофе-дегустация", desc: "Плантация с бесплатной дегустацией 10–12 сортов кофе и чая. Luwak coffee 60k (опция), обзорная на Батур.", mapQuery: "Sila's Agrotourism Kintamani", rating: 4.6, reviews: 1100 },
    ],
    workspaces: [
      { name: "Montana Del Cafe", type: "Кафе с wifi", equipment: "Wifi, розетки, AC внутри, вид на Батур", desc: "Один из немногих кафе с wifi и розетками. 7:00–20:00. Для работы до 19:00 — ок. После темно.", mapQuery: "Montana Del Cafe Kintamani", rating: 4.5, reviews: 900, price: "80–150k" },
      { name: "Paperhills Cafe", type: "Кафе с wifi", equipment: "Wifi, террасы, розетки в части зон", desc: "Популярный cafe с видом на Батур. 9:00–18:00. Вечерняя работа невозможна.", mapQuery: "Paperhills Cafe Kintamani", rating: 4.4, reviews: 1200, price: "100k" },
    ],
    workNote: "Все кафе в Кинтамани закрываются в 18–20:00. После заката работать только из отеля — выбирай заранее с проверенным wifi.",
    days: [
      { date: "16 июня", weekday: "вт", items: [
        { time: "10:00", text: "Выезд Сидемен → Кинтамани (1:30)", emoji: "🛵" },
        { time: "11:30", text: "Заселение" },
        { time: "12:30", text: "Обед в Akasa с видом" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "17 июня", weekday: "ср", items: [
        { time: "9:30", text: "Завтрак в Hills Break" },
        { time: "10:30", text: "Toya Devasya Hot Springs (2 часа)", emoji: "♨️" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "18 июня", weekday: "чт", items: [
        { time: "9:30", text: "Подъём" },
        { time: "10:30", text: "Клубничная ферма — собрать клубнику", emoji: "🍓" },
        { time: "11:30", text: "Kintamani Coffee Plantation — дегустация" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "19 июня", weekday: "пт", title: "Подготовка к Батуру", items: [
        { time: "10:00", text: "Поздний подъём" },
        { time: "11:00", text: "Pura Ulun Danu Batur" },
        { time: "13:00", text: "Обед" },
        { time: "14:00", text: "Работа до 18:00", emoji: "💻" },
        { time: "19:00", text: "Плотный ужин" },
        { time: "20:00", text: "Лечь спать — ранний старт!" },
      ]},
      { date: "20 июня", weekday: "сб", title: "🌋 БАТУР + отдых", isWeekend: true, items: [
        { time: "02:00", text: "Подъём", emoji: "⏰" },
        { time: "03:00", text: "Старт восхождения на Батур 1717 м", emoji: "🌋", highlight: true },
        { time: "05:30", text: "Рассвет на вершине, завтрак из яиц с пара", highlight: true },
        { time: "07:00", text: "Спуск, обезьяны по пути" },
        { time: "10:00", text: "Возврат в отель, душ, спать" },
        { time: "14:00", text: "Поздний обед" },
        { time: "15:00", text: "Бассейн/спа, восстановление" },
        { time: "18:00", text: "Лёгкий ужин, ранний сон" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "amed",
    name: "Амед",
    nights: 5,
    dates: "21–25 июня",
    summary: "Дайвинг у корабля, массаж, йога, коворкинг, русская баня",
    emoji: "🌊",
    color: "ocean",
    spots: [
      { name: "USS Liberty Shipwreck (Tulamben)", desc: "Must-dive. 2 погружения, 15 мин от Амеда", mapQuery: "USAT Liberty Shipwreck Tulamben", tag: "дайв", time: "6:30 старт", cost: "1M IDR за 2 погружения" },
      { name: "Japanese Shipwreck Banyuning", desc: "Малый японский корабль, снорк от берега", mapQuery: "Japanese Shipwreck Banyuning Amed", tag: "снорк", cost: "бесплатно" },
      { name: "Jemeluk Bay Viewpoint", desc: "Смотровая, буквы AMED, закат", mapQuery: "Jemeluk Bay Viewpoint Amed", tag: "смотровая" },
      { name: "Blue Earth Village", desc: "Йога утром + коворкинг с видом на Агунг", mapQuery: "Blue Earth Village Amed", tag: "йога/коворкинг", cost: "150k класс" },
      { name: "Serenity Spa Amed", desc: "Массаж с видом", mapQuery: "Serenity Spa Amed", tag: "спа", cost: "250k/час" },
      { name: "Русская баня", desc: "Стеклянная стена, вид на Агунг. Уточнить адрес на месте", mapQuery: "Russian Banya Amed", tag: "баня" },
      { name: "Amed Salt Farms", desc: "Традиционная добыча соли из моря", mapQuery: "Amed Salt Farms", tag: "культура" },
      { name: "Jemeluk Beach Sunrise", desc: "Восход солнца над морем с видом на Агунг", mapQuery: "Jemeluk Beach Amed", tag: "пляж", time: "05:30" },
      { name: "Lipah Beach Sunset", desc: "Закат в сторону моря", mapQuery: "Lipah Beach Amed", tag: "пляж", time: "закат" },
      { name: "Freediving courses", desc: "Топ-место для фри-дайва на Бали", mapQuery: "Apneista Freediving Amed", tag: "фри-дайв" },
    ],
    cafes: [
      { name: "Warung Vienna", price: "$$", kitchen: "Австрийская", desc: "Must-try. Шницель, гуляш, штрудель — настоящая австрийская классика от австрийца. Чек 100–150k, часто аншлаг.", mapQuery: "Warung Vienna Amed", rating: 4.8, reviews: 450 },
      { name: "Trattoria Amed", price: "$$", kitchen: "Итальянская", desc: "Возможно лучшая пицца восточного Бали. Тонкое тесто, хэнд-мейд пасты, gnocchi, хлеб, вино. Вид на Ибус-бич. 120–180k.", mapQuery: "Trattoria Amed", rating: 4.7, reviews: 1200 },
      { name: "Warung Enak", price: "$", kitchen: "Интернац., балийская", desc: "Центр главной улицы. Индонезийская классика + пиццы и пасты. Хорошие ингредиенты, адекватные цены 60–120k.", mapQuery: "Warung Enak Amed", rating: 4.6, reviews: 900 },
      { name: "Rimba Cafe", price: "$", kitchen: "Healthy бранч", desc: "Smoothie bowls, wraps, бургеры, салаты. Витрина мороженого и кондитерской. Завтрак 50–90k, боулы 70–100k.", mapQuery: "Rimba Cafe Amed", rating: 4.6, reviews: 500 },
      { name: "Cafe Garam", price: "$$", kitchen: "Западная/азиатская", desc: "Отельный ресторан Hotel Uyah. Пиццы (seafood, salami, funghi), западная кухня. Ср/Сб — балийское Genjek. Чек 100–170k.", mapQuery: "Cafe Garam Amed", rating: 4.5, reviews: 600 },
      { name: "Small Time Cooks", price: "$$", kitchen: "Бургеры, бао, фьюжн", desc: "Небольшое место с культовыми бургерами, бао-банами и банан-чай смузи. Быстро, вкусно. Бургер 95k.", mapQuery: "Small Time Cooks Amed", rating: 4.8, reviews: 400 },
      { name: "Good Stuff Cafe", price: "$$", kitchen: "Healthy, веган, кофейня", desc: "Eco-friendly, dog-friendly. Смузи-боулы, салаты, gluten-free. При кафе эко-магазин с рефил-продуктами.", mapQuery: "Good Stuff Cafe Amed", rating: 4.7, reviews: 350 },
      { name: "Melasti Beach Bar", price: "$", kitchen: "Пляжное кафе", desc: "Простое пляжное кафе для завтраков и обедов. Тосты, омлеты, пасты, наси горенг. 50–100k, ноги в песке.", mapQuery: "Melasti Beach Amed", rating: 4.5, reviews: 350 },
      { name: "Warung Segara", price: "$", kitchen: "Рыба, морепродукты", desc: "Пляжный варунг на песке, свежая рыба с лодок. Одни из самых низких цен и лучшая рыба в Амеде.", mapQuery: "Warung Segara Amed", rating: 4.6, reviews: 350 },
      { name: "Sails Restaurant", price: "$$", kitchen: "Западная/морская", desc: "Пляжный ресторан с видом на закат. Пасты, грилленая рыба, салаты, бургеры. Чек 150–220k, вайбы на ужин.", mapQuery: "Sails Restaurant Amed", rating: 4.6, reviews: 700 },
      { name: "Bali Asli", price: "$$$", kitchen: "Fine dining балийская", desc: "Особый ужин. Аутентичная балийская на глиняных печах, вид на Agung. Сет ~400k.", mapQuery: "Bali Asli Amlapura", rating: 4.8, reviews: 550 },
    ],
    workspaces: [
      { name: "Blue Earth Village", type: "Кафе-коворкинг", equipment: "Бесплатный коворкинг, лучший wifi в Амеде, бин-бэги с видом на Джемелук", desc: "Отель-йога-деревня с бесплатной коворкинг-зоной у океана. Ресторан до ~22:00. Лучший вариант для работы допоздна.", mapQuery: "Blue Earth Village Amed", rating: 4.6, reviews: 400, price: "бесплатно (еда/напитки отдельно)" },
      { name: "People Point Cafe", type: "Кафе с wifi", equipment: "Wifi, розетки, AC, большой зал", desc: "Популярный cafe у бухты Липах. До ~22:00. Розетки есть, wifi может пропадать — лучше бэкап через мобильный.", mapQuery: "People Point Cafe Amed", rating: 4.5, reviews: 180, price: "80–120k" },
      { name: "Oneway Espresso", type: "Кафе с wifi", equipment: "Wifi, розетки, спешелти кофе", desc: "Кофейня с хорошим спешелти-кофе. Работает до ~21:00. Комфортно днём и ранним вечером.", mapQuery: "Oneway Espresso Amed", rating: 4.7, reviews: 400, price: "60–100k" },
    ],
    days: [
      { date: "21 июня", weekday: "вс", title: "Переезд после Батура", isWeekend: true, items: [
        { time: "10:00", text: "Подъём, долгий завтрак" },
        { time: "12:00", text: "Выезд Кинтамани → Амед (2:00)", emoji: "🛵" },
        { time: "14:00", text: "Приехали, заселение" },
        { time: "18:00", text: "Лёгкий ужин у моря" },
      ]},
      { date: "22 июня", weekday: "пн", items: [
        { time: "10:00", text: "Массаж (Serenity / Putri)", emoji: "💆" },
        { time: "12:00", text: "Завтрак в Warung Vienna" },
        { time: "14:00", text: "Работа", emoji: "💻" },
        { time: "18:30", text: "Закат на Jemeluk Bay Viewpoint" },
      ]},
      { date: "23 июня", weekday: "вт", items: [
        { time: "9:00", text: "Йога с видом на Агунг (Blue Earth)", emoji: "🧘" },
        { time: "10:30", text: "Завтрак там же" },
        { time: "14:00", text: "Работа из коворкинга", emoji: "💻" },
      ]},
      { date: "24 июня", weekday: "ср", title: "🤿 Дайвинг Liberty", items: [
        { time: "6:30", text: "Подъём" },
        { time: "7:00", text: "Выезд на дайв-центр" },
        { time: "8:00", text: "Два погружения на USS Liberty", emoji: "🤿", highlight: true },
        { time: "11:30", text: "Возврат, обед в Warung Ocean View" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "25 июня", weekday: "чт", title: "🧖 Русская баня", items: [
        { time: "10:00", text: "Подъём" },
        { time: "11:00", text: "Русская баня со стеклянной стеной", emoji: "🧖", highlight: true },
        { time: "13:00", text: "Обед в Warung Bamboo" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "lovina",
    name: "Ловина",
    nights: 3,
    dates: "26–28 июня",
    summary: "Дельфины, Aling-Aling с прыжками, планктон ночью",
    emoji: "🐬",
    color: "ocean",
    spots: [
      { name: "Dolphin boat tour", desc: "04:30 подъём, лодка, дельфины. Заказать накануне", mapQuery: "Lovina Dolphin Tour", tag: "лодка", time: "05:00", cost: "200k/чел" },
      { name: "Aling-Aling Waterfall", desc: "Must. Прыжки 5/10/15 м, горки, дикий 35-м водопад. Гид обязателен", mapQuery: "Aling-Aling Waterfall", tag: "водопад", cost: "125k с гидом" },
      { name: "Gitgit Waterfall", desc: "Классика, можно совместить с Aling-Aling", mapQuery: "Gitgit Waterfall", tag: "водопад", cost: "20k" },
      { name: "Banjar Hot Springs", desc: "Горячие источники в джунглях", mapQuery: "Banjar Hot Spring", tag: "спа", cost: "20k" },
      { name: "Brahmavihara-Arama", desc: "Буддистский монастырь, 30 мин от Ловины", mapQuery: "Brahmavihara Arama Buleleng", tag: "монастырь", cost: "бесплатно" },
      { name: "Singsing Waterfall", desc: "«Двойной» водопад ближе к Ловине", mapQuery: "Singsing Waterfall Lovina", tag: "водопад" },
      { name: "Kalibukbuk Beach", desc: "Чёрный песок, закат", mapQuery: "Kalibukbuk Beach Lovina", tag: "пляж", time: "закат" },
      { name: "Bioluminescent plankton tour", desc: "Лодка после 21:00, светящийся планктон. Сезон май-август ✓", mapQuery: "Lovina Bioluminescent Plankton Tour", tag: "лодка", time: "21:00+", cost: "~300k/чел" },
      { name: "Les Waterfall (Yeh Mampeh)", desc: "60-м водопад, по пути из Амеда", mapQuery: "Les Waterfall Bali", tag: "водопад" },
    ],
    cafes: [
      { name: "Akar Cafe", price: "$", kitchen: "Healthy бранч", desc: "Главное healthy-кафе Ловины. Smoothie bowls, avo toast, веган wraps, банановые блинчики. Кофе на балийских зёрнах. 50–90k.", mapQuery: "Akar Cafe Lovina", rating: 4.7, reviews: 450 },
      { name: "Buda Bakery", price: "$", kitchen: "Пекарня + кафе", desc: "Хлеб, торты, выпечка. Обед: карри, креветки, сэндвичи. Завтрак 40–70k, блюдо 60–100k.", mapQuery: "Buda Bakery Lovina", rating: 4.7, reviews: 969 },
      { name: "Bakery Lovina (German)", price: "$", kitchen: "Немецкая пекарня", desc: "Свежий немецкий хлеб ежедневно, кексы, колбасы, сыр. Традиционный немецкий завтрак у бассейна с брецелем. 60–100k.", mapQuery: "Bakery Lovina", rating: 4.6, reviews: 300 },
      { name: "Coffeenosky", price: "$", kitchen: "Бранч-кафе", desc: "Терраса с видом на рисовые поля. Круассаны, avo toast, eggs benedict, приличный кофе. Завтрак 50–90k, тихо.", mapQuery: "Coffeenosky Lovina", rating: 4.7, reviews: 350 },
      { name: "Semina Lovina", price: "$$", kitchen: "Интернациональная", desc: "Айам бетуту, морская паста, сочные бургеры. Один из стабильно лучших ужинов в Ловине. Чек 120–180k.", mapQuery: "Semina Lovina", rating: 4.6, reviews: 500 },
      { name: "Jasmine Kitchen", price: "$$", kitchen: "Тайская", desc: "Легенда Ловины — настоящая тайская кухня, том-ям, зелёный карри, пад-тай. Чек 80–150k. Закажи заранее.", mapQuery: "Jasmine Kitchen Lovina", rating: 4.8, reviews: 600 },
      { name: "Sea Breeze Cafe", price: "$$", kitchen: "Пляжное интернац.", desc: "Столик на песке, морепродукты, бургеры, пасты, салаты. Лучшее место на закат. Чек 120–180k.", mapQuery: "Sea Breeze Cafe Lovina", rating: 4.5, reviews: 700 },
      { name: "Warung Bambu Pemaron", price: "$$", kitchen: "Балийская легенда", desc: "Must-try в окрестностях. Сет из 12 балийских блюд ~150k, бамбуковый павильон. Одно из лучших аутентичных мест.", mapQuery: "Warung Bambu Pemaron Lovina", rating: 4.7, reviews: 800 },
    ],
    workspaces: [
      { name: "Cafe Leo", type: "Кафе с wifi", equipment: "Wifi, чистые столы, еда, кофе", desc: "Уютный cafe в центре туристической зоны с бесплатным wifi. До ~22:00. Один из немногих адекватных вариантов.", mapQuery: "Cafe Leo Lovina", rating: 4.5, reviews: 220, price: "70–120k" },
      { name: "Lovinalife Room & Cafe", type: "Кафе с wifi", equipment: "Wifi во всех зонах, континентальный завтрак", desc: "Кафе-гостиница с wifi по всей территории. Работает вечером, западная и индонезийская кухня. До ~22:00.", mapQuery: "Lovinalife Room Cafe Lovina", rating: 4.4, reviews: 150, price: "80–150k" },
    ],
    workNote: "В Ловине нет полноценных коворкингов. После 22:00 — из отеля с хорошим wifi.",
    days: [
      { date: "26 июня", weekday: "пт", title: "Переезд из Амеда с остановками", items: [
        { time: "7:30", text: "Подъём, завтрак" },
        { time: "8:30", text: "Выезд Амед → Ловина (3:00)", emoji: "🛵" },
        { time: "", text: "Остановки: Tejakula, Les Waterfall 60м, Air Sanih" },
        { time: "13:00", text: "Приехали, заселение, обед" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "27 июня", weekday: "сб", title: "🎯 Aling-Aling + планктон", isWeekend: true, items: [
        { time: "9:00", text: "Завтрак" },
        { time: "10:00", text: "Aling-Aling Waterfall — прыжки 5/10/15 м", emoji: "🎯", highlight: true },
        { time: "13:00", text: "По пути — Gitgit Waterfall" },
        { time: "14:30", text: "Обед в Secret Garden" },
        { time: "18:30", text: "Закат на Kalibukbuk Beach" },
        { time: "20:00", text: "Ужин в Nia Bar" },
        { time: "21:30", text: "Bioluminescent plankton tour", emoji: "🌙", highlight: true },
      ]},
      { date: "28 июня", weekday: "вс", title: "🐬 Дельфины + Banjar", isWeekend: true, items: [
        { time: "4:30", text: "Подъём", emoji: "⏰" },
        { time: "5:00", text: "Лодка на дельфинов", emoji: "🐬", highlight: true },
        { time: "7:00", text: "Завтрак в The Damai / Buddha Banana" },
        { time: "10:00", text: "Banjar Hot Springs", emoji: "♨️" },
        { time: "12:00", text: "Brahmavihara-Arama монастырь" },
        { time: "13:30", text: "Обед, отдых" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "pemuteran",
    name: "Пемутеран",
    nights: 2,
    dates: "29–30 июня",
    summary: "Menjangan Island snorkeling, Biorock, черепахи, тихо",
    emoji: "🐢",
    color: "ocean",
    spots: [
      { name: "Menjangan Island snorkel/dive", desc: "Must. Лучший риф Бали, West Bali National Park. Лодка 8:00, 2–3 часа", mapQuery: "Menjangan Island Bali", tag: "снорк/дайв", cost: "400–600k/чел" },
      { name: "Biorock Pemuteran", desc: "Искусственный коралловый риф у берега, снорк бесплатно", mapQuery: "Biorock Pemuteran Bay", tag: "снорк", cost: "бесплатно" },
      { name: "Reef Seen Turtle Project", desc: "Центр спасения черепах, можно выпустить молодь", mapQuery: "Reef Seen Turtle Project Pemuteran", tag: "черепахи", cost: "~50k" },
      { name: "West Bali National Park", desc: "Джунгли, балийский скворец-эндемик, трекинг", mapQuery: "West Bali National Park", tag: "парк" },
      { name: "Pemuteran Beach sunset", desc: "Чёрный песок, тишина", mapQuery: "Pemuteran Beach", tag: "пляж", time: "закат" },
      { name: "Pulaki Temple", desc: "Храм с семьёй обезьян", mapQuery: "Pulaki Temple Bali", tag: "храм", cost: "бесплатно" },
      { name: "Jayaprana Tomb", desc: "Легендарная могила, смотровая", mapQuery: "Jayaprana Tomb Bali", tag: "смотровая" },
    ],
    cafes: [
      { name: "Selini Cafe & Bakery", price: "$$", kitchen: "Пекарня + кафе", desc: "Главная пекарня локации. Хлеб, круассаны, тортики, завтраки, сэндвичи. Open-air зал, морской бриз. Чек 80–130k.", mapQuery: "Selini Cafe Bakery Pemuteran", rating: 4.6, reviews: 300 },
      { name: "K&A Grill", price: "$$", kitchen: "Интернациональный фьюжн", desc: "Фьюжн индонезийского и интернационального. Грилл, пасты, салаты, морепродукты. Уютная веранда. Чек 120–180k.", mapQuery: "K&A Grill Pemuteran", rating: 4.7, reviews: 500 },
      { name: "Warung Sari Kembang", price: "$", kitchen: "Балийская легенда", desc: "Must-try warung деревни. Наси кампур, айам бакар, сате с идеальными домашними соусами. Блюдо 30–60k.", mapQuery: "Warung Sari Kembang Pemuteran", rating: 4.7, reviews: 450 },
      { name: "Amerta Sunset Beach", price: "$$", kitchen: "Пляжное интернац.", desc: "Столики в песке на закат. Пиццы, пасты, гриль из рыбы, бургеры. Чек 100–170k.", mapQuery: "Amerta Sunset Beach Warung Pemuteran", rating: 4.6, reviews: 400 },
      { name: "Kubuku Ecolodge", price: "$$", kitchen: "Вегетарианская/интернац.", desc: "Экологичный ресторан с большим вегетарианским меню. Карри, пасты, салаты, свежие соки. Чек 100–160k.", mapQuery: "Kubuku Ecolodge Pemuteran", rating: 4.7, reviews: 350 },
      { name: "Adi Assri Restaurant", price: "$$", kitchen: "Континентальная/европ.", desc: "Отельный ресторан в бухте. Балийская, континентальная, американская, европейская кухня. Чек 120–180k.", mapQuery: "Adi Assri Beach Resort Pemuteran", rating: 4.5, reviews: 600 },
      { name: "La Casa Kita", price: "$$", kitchen: "Итальянская, пицца", desc: "Пицца из дровяной печи, La Casa Coco Tuna, Regina. Лайв-музыка, ухоженный газон.", mapQuery: "La Casa Kita Pemuteran", rating: 4.5, reviews: 480 },
      { name: "Bali Balance Cafe", price: "$$", kitchen: "Кофейня, веган, healthy", desc: "Говорят — лучший кофе на Бали. Скрыт в тропическом саду. Морковный торт, свежие соки, выпечка. Обязательное для завтрака.", mapQuery: "Bali Balance Cafe Pemuteran", rating: 4.7, reviews: 600 },
    ],
    workspaces: [
      { name: "Eco Taste Cafe", type: "Кафе с wifi", equipment: "Wifi, розетки, AC, тихо, музыка", desc: "По отзывам digital-nomad friendly. Работает до ~21:00. Лучший вариант в Пемутеране, после 21 — из отеля.", mapQuery: "Eco Taste Cafe Pemuteran", rating: 4.5, reviews: 120, price: "70–120k" },
    ],
    workNote: "В Пемутеране нет коворкингов. Вечером и ночью работать только из отеля (выбирай Matahari Beach, Taman Sari, Puri Ganesha — у них проверенный wifi).",
    days: [
      { date: "29 июня", weekday: "пн", items: [
        { time: "10:00", text: "Выезд Ловина → Пемутеран (1:15)", emoji: "🛵" },
        { time: "11:30", text: "Заселение" },
        { time: "12:00", text: "Biorock — снорк у берега", emoji: "🐠" },
        { time: "12:30", text: "Reef Seen Turtle Project", emoji: "🐢" },
        { time: "13:30", text: "Обед в Warung Kayu Manis" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "30 июня", weekday: "вт", title: "🤿 Menjangan Island", items: [
        { time: "7:00", text: "Подъём, лёгкий завтрак" },
        { time: "7:30", text: "На пирсе, лодка в West Bali NP" },
        { time: "8:00", text: "Snorkel / dive Menjangan", emoji: "🤿", highlight: true },
        { time: "12:30", text: "Возврат, обед в Seasalt" },
        { time: "14:00", text: "Работа", emoji: "💻" },
        { time: "19:00", text: "Ужин в The Kawi" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "munduk",
    name: "Мундук",
    nights: 3,
    dates: "1–3 июля",
    summary: "Водопады, озёра Буян/Тамблинган, храм Ulun Danu Beratan",
    emoji: "⛰",
    color: "jungle",
    spots: [
      { name: "Munduk Waterfall", desc: "Классика, лёгкий трек 15 мин", mapQuery: "Munduk Waterfall", tag: "водопад", cost: "20k" },
      { name: "Melanting Waterfall", desc: "Рядом с Мундук-водопадом, совмещённый трек", mapQuery: "Melanting Waterfall Munduk", tag: "водопад" },
      { name: "Red Coral Waterfall", desc: "Малоизвестный, фотогеничный", mapQuery: "Red Coral Waterfall Munduk", tag: "водопад" },
      { name: "Banyumala Twin Waterfall", desc: "Двойной водопад, одно из самых красивых мест Бали", mapQuery: "Banyumala Twin Waterfall", tag: "водопад", cost: "30k" },
      { name: "Twin Lakes Viewpoint (Wanagiri)", desc: "Панорама на Буян и Тамблинган", mapQuery: "Twin Lake Viewpoint Munduk", tag: "смотровая" },
      { name: "Wanagiri Hidden Hills", desc: "«Гнёзда» и качели для фото", mapQuery: "Wanagiri Hidden Hills", tag: "фото", cost: "50k" },
      { name: "Danau Buyan", desc: "Прогулка по берегу, каноэ", mapQuery: "Danau Buyan Bali", tag: "озеро" },
      { name: "Danau Tamblingan", desc: "Тихое священное озеро, каноэ", mapQuery: "Danau Tamblingan", tag: "озеро" },
      { name: "Pura Ulun Danu Beratan", desc: "Легендарный храм на озере. MUST на закате. 30 мин от Мундука", mapQuery: "Ulun Danu Beratan Temple", tag: "храм", time: "закат", cost: "75k" },
      { name: "Bali Handara Gate", desc: "Инстаграмные «ворота в небо». Очередь за фото 20 мин", mapQuery: "Bali Handara Gate", tag: "фото", cost: "50k" },
      { name: "Munduk Village Walk", desc: "Прогулка по деревне с гидом", mapQuery: "Munduk Village", tag: "прогулка" },
    ],
    cafes: [
      { name: "Ngiring Ngewedang", price: "$$", kitchen: "Балийская с видом", desc: "Терраса над долиной Мундука. Завтраки с панорамой, сатай, карри, индонезийские блюда + пасты и сэндвичи. Чек 80–150k.", mapQuery: "Ngiring Ngewedang Munduk", rating: 4.6, reviews: 600 },
      { name: "Don Biu", price: "$$", kitchen: "Пиццерия / интернац.", desc: "Дровяная пицца в горах, пасты, салаты, бургеры. Достойный итальянский уровень для такой отдалённой локации. Чек 100–170k.", mapQuery: "Don Biu Munduk", rating: 4.6, reviews: 450 },
      { name: "The View Munduk", price: "$$", kitchen: "Интернациональная", desc: "10 минут от центра. Панорама гор и Яванского моря. Вегетарианские опции, пасты, тайская. Чек 100–170k.", mapQuery: "The View Munduk", rating: 4.7, reviews: 500 },
      { name: "Warung Kadirasa", price: "$", kitchen: "Балийская легенда", desc: "Must-try семейный warung Мундука. Настоящая балийская — наси кампур, лавар, сатай с домашними соусами. Блюдо 30–60k.", mapQuery: "Warung Kadirasa Munduk", rating: 4.8, reviews: 350 },
      { name: "Eco Cafe 2", price: "$", kitchen: "Органик", desc: "Кооператив местных фермеров, органическое меню. Локальный кофе, завтраки, карри, салаты. Блюдо 50–90k.", mapQuery: "Eco Cafe 2 Munduk", rating: 4.7, reviews: 300 },
      { name: "Terrasse du Lac Tamblingan", price: "$$", kitchen: "Интернац., бранч", desc: "Столик над озером Тамблинган. Завтраки, сэндвичи, пасты, индонезийская классика. Чек 100–170k.", mapQuery: "Terrasse du Lac Munduk", rating: 4.6, reviews: 350 },
      { name: "Puri Lumbung Cafe", price: "$$", kitchen: "Индонезийская/европ.", desc: "Отельный ресторан с видом на террасы. Свежие соки, завтраки, сэндвичи, пасты. Чек 100–150k.", mapQuery: "Puri Lumbung Munduk", rating: 4.6, reviews: 400 },
    ],
    workspaces: [],
    workNote: "В Мундуке нет коворкингов и нормальных laptop-friendly кафе. Рестораны с wifi (Ngiring Ngewedang, Don Biu, Puri Lumbung) закрываются к 21:00 и столы не рабочие. Для серьёзной работы до 22–23:00 — только из отеля. Ищи виллу с подтверждённым wifi.",
    days: [
      { date: "1 июля", weekday: "ср", items: [
        { time: "9:00", text: "Выезд Пемутеран → Мундук (2:30)", emoji: "🛵" },
        { time: "11:30", text: "Заселение" },
        { time: "12:00", text: "Обед в Ngiring Ngewedang" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "2 июля", weekday: "чт", title: "Водопады", items: [
        { time: "9:30", text: "Завтрак в Don Biyu" },
        { time: "10:30", text: "Munduk + Melanting водопады (1.5 ч)", emoji: "💦" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "3 июля", weekday: "пт", title: "Озёра + храм на закат", items: [
        { time: "9:00", text: "Подъём" },
        { time: "10:00", text: "Twin Lakes Viewpoint" },
        { time: "10:30", text: "Wanagiri Hidden Hills (20 мин)" },
        { time: "11:30", text: "Banyumala Twin Waterfall", emoji: "💦" },
        { time: "14:00", text: "Работа", emoji: "💻" },
        { time: "18:00", text: "Pura Ulun Danu Beratan на закате", emoji: "🏯", highlight: true },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "jatiluwih",
    name: "Джатилувих",
    nights: 2,
    dates: "4–5 июля",
    summary: "UNESCO террасы, храм Батукару, тишина",
    emoji: "🌾",
    color: "jungle",
    spots: [
      { name: "Jatiluwih Rice Terraces", desc: "UNESCO. Трек-маршруты (красный/жёлтый/синий), 1–3 часа", mapQuery: "Jatiluwih Rice Terrace", tag: "природа", cost: "40k вход" },
      { name: "Pura Luhur Batukaru", desc: "Второй по значимости храм после Besakih, среди джунглей", mapQuery: "Pura Luhur Batukaru", tag: "храм", cost: "бесплатно, донат" },
      { name: "Leke Leke Waterfall", desc: "Спрятанный водопад в джунглях, 40 мин", mapQuery: "Leke Leke Waterfall", tag: "водопад", cost: "50k" },
      { name: "Yeh Hoo Waterfall", desc: "Каскад, мало людей", mapQuery: "Yeh Hoo Waterfall", tag: "водопад" },
      { name: "Gunung Batukaru trek", desc: "Восхождение 2276м, серьёзный трек (для энтузиастов)", mapQuery: "Mount Batukaru", tag: "трек" },
      { name: "Pupuan Rice Terraces", desc: "Ещё одни террасы, менее известные", mapQuery: "Pupuan Rice Terrace", tag: "природа" },
      { name: "Cycling по террасам", desc: "Велопрокат при Jatiluwih Visitor Center", mapQuery: "Jatiluwih Visitor Center", tag: "вело" },
    ],
    cafes: [
      { name: "Billy's Terrace Cafe", price: "$$", kitchen: "Интернац., балийская", desc: "Лучшая точка обзора рисовых террас. Буфет и a la carte: западные и балийские блюда. Чек 120–180k.", mapQuery: "Billy's Terrace Cafe Jatiluwih", rating: 4.5, reviews: 450 },
      { name: "Batu Karu Kopi", price: "$$", kitchen: "Кофейня, бранч, healthy", desc: "Независимая кофейня со своей обжаркой, 100% органическая арабика с собственной фермы в 2 км. Бранч и выпечка, вид на Batukaru.", mapQuery: "Batu Karu Kopi Jatiluwih", rating: 4.8, reviews: 240 },
      { name: "Gong Jatiluwih", price: "$", kitchen: "Балийская", desc: "Локальная классика — расслабленная атмосфера, балийский комфорт-фуд. Наси горенг, карри, сатай. Блюдо 40–80k.", mapQuery: "Gong Jatiluwih Restaurant", rating: 4.5, reviews: 600 },
      { name: "Bhuana Agung", price: "$$", kitchen: "Индонез./интернац.", desc: "Открытая терраса над рисовыми полями — один из лучших видов. Пасты, пиццы, индонезийская классика. Чек 100–170k.", mapQuery: "Bhuana Agung Jatiluwih", rating: 4.5, reviews: 400 },
      { name: "The Gafel Okokan", price: "$", kitchen: "Кафе бранч", desc: "Cafe-вайб среди полей. Завтраки, smoothie bowls, сэндвичи, кофе. Блюдо 60–100k — редкий кафе-формат для Джатилувих.", mapQuery: "The Gafel Okokan Jatiluwih", rating: 4.6, reviews: 250 },
      { name: "Warung Dhea", price: "$", kitchen: "Балийская семейная", desc: "Must-try — семейный warung с локальными ингредиентами. Настоящая балийская кухня без туристических компромиссов. Блюдо 35–70k.", mapQuery: "Warung Dhea Jatiluwih", rating: 4.7, reviews: 220 },
    ],
    workspaces: [],
    workNote: "Все рестораны с видом (Billy's Terrace, Gong Jatiluwih, Warung Dhea) закрываются в 17–20:00. Для работы после обеда до ночи — только из отеля. Рекомендую Sang Giri или Cempaka Belimbing — у них подтверждённо быстрый wifi.",
    days: [
      { date: "4 июля", weekday: "сб", title: "🎯 Террасы + храм Батукару", isWeekend: true, items: [
        { time: "8:30", text: "Завтрак" },
        { time: "9:30", text: "Выезд Мундук → Джатилувих (1:30)", emoji: "🛵" },
        { time: "11:00", text: "Заселение" },
        { time: "11:30", text: "Jatiluwih Rice Terraces trekking", emoji: "🌾", highlight: true },
        { time: "13:30", text: "Обед в Gong Jatiluwih с панорамой" },
        { time: "15:00", text: "Pura Luhur Batukaru — храм в джунглях", emoji: "🏯", highlight: true },
        { time: "19:00", text: "Ужин" },
      ]},
      { date: "5 июля", weekday: "вс", title: "Водопад + отдых", isWeekend: true, items: [
        { time: "9:30", text: "Бассейн, завтрак" },
        { time: "11:00", text: "Leke Leke Waterfall (40 мин)", emoji: "💦" },
        { time: "13:00", text: "Обед в DHistory / Sang Giri" },
        { time: "14:00", text: "Отдых, прогулка по террасам" },
        { time: "18:00", text: "Закат на террасах" },
        { time: "20:00", text: "Ужин при свечах / костёр" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "seminyak",
    name: "Семиньяк",
    nights: 2,
    dates: "6–7 июля",
    summary: "Буфер перед вылетом, закаты, прощальный ужин",
    emoji: "🏖",
    color: "sunset",
    spots: [
      { name: "Potato Head Beach Club", desc: "Must. Закат, архитектура", mapQuery: "Potato Head Beach Club", tag: "beach club", time: "закат" },
      { name: "La Brisa Canggu", desc: "Beach club био-стиль", mapQuery: "La Brisa Canggu", tag: "beach club", time: "закат" },
      { name: "Seminyak Beach", desc: "Длинный пляж у Potato Head", mapQuery: "Seminyak Beach", tag: "пляж" },
      { name: "Seminyak Square", desc: "Шопинг, бренды", mapQuery: "Seminyak Square", tag: "шопинг" },
      { name: "Double Six Beach", desc: "Пляж с barlife", mapQuery: "Double Six Beach", tag: "пляж" },
      { name: "Tanah Lot", desc: "Храм на скале, 40 мин от Семиньяка, закат", mapQuery: "Tanah Lot", tag: "храм", time: "закат", cost: "60k" },
      { name: "Ku De Ta", desc: "Легендарный beach club", mapQuery: "Ku De Ta Seminyak", tag: "beach club" },
      { name: "Petitenget Beach", desc: "Тише, без толпы", mapQuery: "Petitenget Beach", tag: "пляж" },
    ],
    cafes: [
      { name: "Sisterfields", price: "$$", kitchen: "Австралийский бранч", desc: "Икона бранча Семиньяка. Eggs benedict, avocado toast, пэнкейки, сэндвичи, отличный кофе. Чек 120–180k, часто очередь утром.", mapQuery: "Sisterfields Cafe Seminyak", rating: 4.5, reviews: 3200 },
      { name: "KYND Community", price: "$$", kitchen: "Plant-based бранч", desc: "Знаменитые смузи-боулы с надписями из манго, веган завтраки, сэндвичи. Розовая эстетика. Боул 80–130k, блюдо 100–170k.", mapQuery: "KYND Community Seminyak", rating: 4.5, reviews: 2800 },
      { name: "Monsieur Spoon", price: "$", kitchen: "Французская пекарня", desc: "Круассаны, pain au chocolat 52k, quiche lorraine 79k, багеты. Лёгкий французский завтрак по честной цене.", mapQuery: "Monsieur Spoon Seminyak", rating: 4.5, reviews: 1400 },
      { name: "Livingstone Cafe", price: "$$", kitchen: "Пекарня + бранч", desc: "Свежие круассаны каждый день, тёплые прямо из печи. Бранч, пасты, сэндвичи. Чек 100–170k.", mapQuery: "Livingstone Cafe Seminyak", rating: 4.5, reviews: 2100 },
      { name: "BAKED Bali", price: "$$", kitchen: "Пекарня + кафе", desc: "Современная пекарня-кафе родом из Чангу. Известна Best Scramble и хорошим кофе. Выпечка 40–80k, блюдо 90–150k.", mapQuery: "BAKED Bali Seminyak", rating: 4.6, reviews: 800 },
      { name: "Cafe Organic", price: "$", kitchen: "Vegan healthy", desc: "100% веган. Смузи-боулы 65–75k, пляжный декор, уютная витрина. Лёгкое место на каждый день.", mapQuery: "Cafe Organic Seminyak", rating: 4.5, reviews: 1600 },
      { name: "Petitenget", price: "$$", kitchen: "Французское бистро", desc: "Casual chic бистро для завтрака и кофе. Любим экспатами и путешественниками. Круассаны, eggs, бранч-блюда. Чек 120–180k.", mapQuery: "Petitenget Restaurant Seminyak", rating: 4.5, reviews: 1900 },
      { name: "Hut Bali", price: "$$", kitchen: "Средиземноморская", desc: "Modern Middle Eastern и Mediterranean в деревянном joglo. Своя пекарня. Мезе, хумус, шакшука. Чек 120–180k.", mapQuery: "Hut Bali Seminyak", rating: 4.6, reviews: 600 },
      { name: "Wild Habit Pizza", price: "$$", kitchen: "Итальянская пиццерия", desc: "Аутентичная итальянская. Пиццы 100–160k, пасты 90–150k, хорошее вино. Лайтовая атмосфера на ужин.", mapQuery: "Wild Habit Pizza Seminyak", rating: 4.6, reviews: 900 },
      { name: "Ingka Kitchen", price: "$", kitchen: "Интернац. бранч", desc: "Дружелюбное место, завтраки до 15:00, чайник балийского кофе 30k. Блюдо 60–120k, приятный бюджетный бранч.", mapQuery: "Ingka Kitchen Seminyak", rating: 4.6, reviews: 450 },
      { name: "Doppio Cafe Pink", price: "$", kitchen: "Healthy бранч", desc: "Смузи-боул 60k: фрукты, гранола, кокос, орехи. Веган-френдли, дэйри-фри. На Sunset Road, бюджетно.", mapQuery: "Doppio Cafe Pink Seminyak", rating: 4.6, reviews: 700 },
      { name: "Nalu Bowls", price: "$", kitchen: "Smoothie bowls", desc: "Легендарные smoothie bowls Бали. Acai, pitaya, Tropical bowls. Простой формат, большие порции, свежие фрукты.", mapQuery: "Nalu Bowls Seminyak", rating: 4.4, reviews: 560 },
      { name: "Mamasan", price: "$$$", kitchen: "Asian fine dining", desc: "Особый ужин. Дим-сам, тайка, индонезийская кухня в колониальном интерьере. Ужин ~350k.", mapQuery: "Mamasan Seminyak", rating: 4.6, reviews: 3100 },
    ],
    workspaces: [
      { name: "Biliq Bali", type: "Коворкинг", equipment: "Pay-per-minute, быстрый wifi, розетки, бассейн с lap-desks", desc: "Первый на Бали коворкинг с оплатой по минутам. Работает до 22:00. Уникальные плавучие lap-desks в бассейне.", mapQuery: "Biliq Bali Seminyak", rating: 4.5, reviews: 250, price: "~100–150k/день (по минутам)" },
      { name: "KE{M}BALI Innovation Hub", type: "Коворкинг", equipment: "Dedicated desks, переговорки, wifi, кофе/чай", desc: "Креативный хаб на Sunset Road с переговорками и ивентами. До 22:00. Хорош для длинных рабочих сессий.", mapQuery: "KEMBALI Innovation Hub Seminyak", rating: 4.6, reviews: 200, price: "150k/день" },
      { name: "Revolver Espresso", type: "Кафе с wifi", equipment: "Быстрый wifi, розетки, спешелти кофе, AC", desc: "Легендарная кофейня, 7:00–23:00. Топ для digital nomad-ов: сильный wifi, розетки, можно засесть на вечер.", mapQuery: "Revolver Espresso Seminyak", rating: 4.6, reviews: 3800, price: "100–200k чек" },
      { name: "32do Bali", type: "Кафе с wifi", equipment: "Wifi, розетки, AC, стильный интерьер", desc: "Современный laptop-friendly cafe. До ~22–23:00. Удобные столы, тихая атмосфера, стабильный wifi.", mapQuery: "32do Bali Seminyak", rating: 4.5, reviews: 300, price: "120–180k" },
    ],
    days: [
      { date: "6 июля", weekday: "пн", items: [
        { time: "10:00", text: "Выезд Джатилувих → Семиньяк (2:00)", emoji: "🛵" },
        { time: "12:00", text: "Заселение" },
        { time: "13:00", text: "Обед в Sisterfields" },
        { time: "14:00", text: "Работа", emoji: "💻" },
        { time: "20:00", text: "Ужин в La Lucciola" },
      ]},
      { date: "7 июля", weekday: "вт", title: "Прощание с Бали", items: [
        { time: "9:30", text: "Бассейн / пляж" },
        { time: "11:00", text: "Шопинг на Seminyak Square" },
        { time: "14:00", text: "Работа (последний день)", emoji: "💻" },
        { time: "18:00", text: "Закат в Potato Head / La Brisa", emoji: "🌅", highlight: true },
        { time: "20:30", text: "Прощальный ужин: Merah Putih / Sarong / Mama San" },
      ]},
    ],
  },
];

export function getPlace(slug: string): Place | undefined {
  return PLACES.find((p) => p.slug === slug);
}
