import type { Place } from "./types";

export const TRIP_META = {
  start: "9 июня 2026",
  end: "8 июля 2026",
  totalNights: 29,
  travelers: 2,
  workingHours: "с 14:00 до ночи по будням",
};

// Главные точки маршрута (для карты)
export const ROUTE_POINTS = [
  "Seminyak, Bali, Indonesia",
  "Ubud, Bali, Indonesia",
  "Sidemen, Karangasem, Bali, Indonesia",
  "Kintamani, Bangli, Bali, Indonesia",
  "Amed, Karangasem, Bali, Indonesia",
  "Lovina Beach, Buleleng, Bali, Indonesia",
  "Pemuteran, Buleleng, Bali, Indonesia",
  "Munduk, Buleleng, Bali, Indonesia",
  "Jatiluwih, Tabanan, Bali, Indonesia",
  "Seminyak, Bali, Indonesia",
];

// Координаты каждой локации (lat, lon) — для карты в app
export const PLACE_COORDS: Record<string, { lat: number; lon: number }> = {
  seminyak: { lat: -8.6898, lon: 115.1711 },
  ubud: { lat: -8.5069, lon: 115.2625 },
  sidemen: { lat: -8.4556, lon: 115.4492 },
  kintamani: { lat: -8.2778, lon: 115.3525 },
  amed: { lat: -8.3400, lon: 115.6864 },
  lovina: { lat: -8.1583, lon: 115.0283 },
  pemuteran: { lat: -8.1425, lon: 114.6517 },
  munduk: { lat: -8.2628, lon: 115.0681 },
  jatiluwih: { lat: -8.3706, lon: 115.1367 },
};

// Bounding box Бали (для OSM embed)
export const BALI_BBOX = "114.40,-8.87,115.72,-8.03";

export const PLACES: Place[] = [
  // =========================================================
  {
    slug: "ubud",
    name: "Убуд",
    nights: 5,
    dates: "9–13 июня",
    summary: "Лес обезьян, рисовые террасы, Cretya, водопады, йога",
    emoji: "🌿",
    color: "jungle",
    spots: [
      { name: "Monkey Forest", desc: "Лес обезьян. Открытие 9:00, к 10 народ. Прячь очки и телефоны", mapQuery: "Sacred Monkey Forest Sanctuary Ubud", tag: "парк", time: "утро", cost: "80k IDR" },
      { name: "Tegalalang Rice Terraces", desc: "Классика рисовых террас. К 8:00 без толпы", mapQuery: "Tegalalang Rice Terrace", tag: "природа", time: "утро", cost: "25k IDR" },
      { name: "Campuhan Ridge Walk", desc: "Лёгкий трек по холму, 1 час, бесплатно", mapQuery: "Campuhan Ridge Walk Ubud", tag: "прогулка", time: "утро/закат" },
      { name: "Tibumana Waterfall", desc: "Один красивый водопад, озерцо для купания, 45 мин от Убуда", mapQuery: "Tibumana Waterfall", tag: "водопад", cost: "20k IDR" },
      { name: "Tegenungan Waterfall", desc: "Ближе к Убуду, более туристический", mapQuery: "Tegenungan Waterfall", tag: "водопад", cost: "20k IDR" },
      { name: "Cretya Ubud Day Club", desc: "Бассейн, коктейли, идеально на закат", mapQuery: "Cretya Ubud", tag: "day club", time: "с обеда до заката", cost: "300k+ minimum spend" },
      { name: "Yoga Barn", desc: "Культовая йога-студия, классы с 7:30", mapQuery: "The Yoga Barn Ubud", tag: "йога", cost: "150k IDR класс" },
      { name: "Ubud Art Market", desc: "Сувениры, торговаться обязательно", mapQuery: "Ubud Traditional Art Market", tag: "рынок" },
      { name: "Saraswati Temple", desc: "Храм с прудом лотосов, бесплатно, 10 мин", mapQuery: "Pura Taman Saraswati Ubud", tag: "храм", cost: "бесплатно" },
      { name: "Goa Gajah (Elephant Cave)", desc: "Древний храм-пещера, 30 мин от Убуда", mapQuery: "Goa Gajah Ubud", tag: "храм", cost: "50k IDR" },
      { name: "Tirta Empul", desc: "Храм со священной водой, ритуал, саронг в аренду", mapQuery: "Tirta Empul Temple", tag: "храм", cost: "50k IDR" },
    ],
    cafes: [
      // 🇷🇺 Русская / восточноевропейская еда
      { name: "Draniki Ubud", price: "$$", kitchen: "🇷🇺 Восточноевропейская", desc: "Драники, борщ, пельмени, котлеты. Открыто до 22:00.", mapQuery: "Draniki Ubud", rating: 4.7, reviews: 593 },
      { name: "Soul Kitchen", price: "$$", kitchen: "🇷🇺 Ресторан (постсоветский)", desc: "Большое ежедневное место с русскоязычной публикой. Стабильно высокий рейтинг. До 22:00.", mapQuery: "Soul Kitchen Ubud", rating: 4.6, reviews: 1402 },
      { name: "Bukhara Chaikhana Bali", price: "$$", kitchen: "🇷🇺 Узбекская чайхана", desc: "Плов, манты, шурпа, лагман, самса. Восточная атмосфера. До 22:00.", mapQuery: "Bukhara Chaikhana Bali Ubud", rating: 4.6, reviews: 309 },
      { name: "SkaZka Bali", price: "$$", kitchen: "🇷🇺 Ресторан", desc: "Домашняя русская кухня, русскоязычное меню. Отзывов мало (103), но рейтинг топ.", mapQuery: "SkaZka Bali Ubud", rating: 4.9, reviews: 103 },
      // Интернациональная еда
      { name: "Milk & Madu Ubud", price: "$$", kitchen: "Австралийский бранч, кафе", desc: "Классика Убуда: пицца, бургеры, бранч. Eggs benedict, burrito, будничные сеты.", mapQuery: "Milk and Madu Ubud", rating: 4.5, reviews: 5673 },
      { name: "Monsieur Spoon Ubud", price: "$$", kitchen: "Французская пекарня", desc: "Круассаны, pain au chocolat, quiche, багеты. Открывается с 06:30. Тихий сад.", mapQuery: "Monsieur Spoon Ubud", rating: 4.5, reviews: 2813 },
      { name: "Pizza Bagus", price: "$$", kitchen: "Пиццерия", desc: "Убудская классика с 1996. Пиццы и пасты 80–140k. Открыто до 22:30.", mapQuery: "Pizza Bagus Ubud", rating: 4.3, reviews: 2674 },
      { name: "Hujan Locale", price: "$$$", kitchen: "Современная индонезийская", desc: "Особый ужин. Шеф Will Meyrick — стрит-фуд Азии в упакованной подаче. Чек 250k+/чел. Бронь.", mapQuery: "Hujan Locale Ubud", rating: 4.6, reviews: 2300 },
      { name: "Warung Gauri", price: "$", kitchen: "Индийская / сатэ", desc: "Аутентичная индийская: тали, карри, дал, свежие роти. Бюджетно и ароматно.", mapQuery: "Warung Gauri Ubud", rating: 4.6, reviews: 2088 },
      { name: "Yellow Flower Café", price: "$$", kitchen: "Healthy кафе", desc: "Скрытый органик-кафе с видом на джунгли. Healthy завтраки. Откр. с 07:00.", mapQuery: "Yellow Flower Cafe Ubud", rating: 4.4, reviews: 1469 },
      { name: "La Luz Ubud", price: "$$", kitchen: "Мексиканская", desc: "Мексиканский ресторан. Открыто до 00:00 — один из самых поздних в Убуде. Высокий рейтинг.", mapQuery: "La Luz Ubud", rating: 4.8, reviews: 1200 },
      { name: "Melali Ubud", price: "$$", kitchen: "Ресторан, healthy", desc: "Завтраки весь день, тихая веранда. Работает до 23:00. Подальше от туристической суеты.", mapQuery: "Melali Ubud", rating: 4.7, reviews: 999 },
      { name: "ShamanaMama", price: "$$", kitchen: "Кафе, healthy/веган", desc: "Vegan-friendly кафе в джунглях. Smoothie bowls, боулы, супы. До 22:00.", mapQuery: "ShamanaMama Restaurant Ubud", rating: 4.6, reviews: 671 },
      { name: "Mango Cafe", price: "$$", kitchen: "Ресторан, бранч", desc: "Завтраки, смузи, сэндвичи, бургеры. Laid-back место на каждый день.", mapQuery: "Mango Cafe Ubud", rating: 4.6, reviews: 431 },
      { name: "Mana Kitchen", price: "$$", kitchen: "Healthy fusion", desc: "Healthy-кафе с азиатскими акцентами. Боулы, карри, салаты, соки.", mapQuery: "Mana Kitchen Ubud", rating: 4.4, reviews: 310 },
    ],
    workspaces: [
      { name: "Ubud.Space Coworking and Coffee", type: "Коворкинг", equipment: "Wifi, розетки, тихие зоны, кофе", desc: "Официальный коворкинг. Работает до 23:30 — подходит для работы допоздна.", mapQuery: "Ubud Space Coworking Coffee", rating: 4.7, reviews: 266, price: "~120k/день" },
      { name: "Ubud Co-Working", type: "Коворкинг", equipment: "Wifi, розетки, переговорки, AC", desc: "Классический коворкинг с дневными пропусками. Работает до 23:00. Отзывов пока немного.", mapQuery: "Ubud Co-Working", rating: 4.6, reviews: 67, price: "~150k/день" },
      { name: "Laduma Ubud", type: "Кафе-коворкинг", equipment: "Wifi, тихая атмосфера, кофе", desc: "Современное кафе с очень высоким рейтингом. Подходит для работы днём с ноутом.", mapQuery: "Laduma Ubud", rating: 4.8, reviews: 185, price: "средний чек" },
    ],
    days: [
      { date: "9 июня", weekday: "вт", title: "Приезд в Убуд", items: [
        { time: "10:00", text: "Выезд из Семиньяка", emoji: "🛵" },
        { time: "12:00", text: "Заселение, обед в Clear Café" },
        { time: "14:00", text: "Работа", emoji: "💻" },
        { time: "18:30", text: "Campuhan Ridge Walk на закат" },
      ]},
      { date: "10 июня", weekday: "ср", items: [
        { time: "9:30", text: "Подъём, завтрак в Milk & Madu" },
        { time: "10:30", text: "Seniman Coffee — работа с ноута" },
        { time: "13:00", text: "Обед в Watercress" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "11 июня", weekday: "чт", items: [
        { time: "9:00", text: "Monkey Forest к открытию", emoji: "🐒" },
        { time: "10:30", text: "Завтрак в Alchemy" },
        { time: "12:00", text: "Jalan Hanoman / Jalan Dewi Sita — магазины" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "12 июня", weekday: "пт", items: [
        { time: "8:30", text: "Tegalalang Rice Terraces — до толпы", emoji: "🌾" },
        { time: "10:00", text: "Завтрак в Tis Café" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "13 июня", weekday: "сб", title: "Cretya + водопад", isWeekend: true, items: [
        { time: "9:30", text: "Завтрак в Hujan Locale" },
        { time: "11:00", text: "Tibumana Waterfall", emoji: "💦" },
        { time: "14:00", text: "Обед в Bebek Tepi Sawah" },
        { time: "15:30", text: "Cretya Ubud Day Club до заката", emoji: "🎯", highlight: true },
        { time: "20:00", text: "Ужин в Locavore / Naughty Nuri's" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "sidemen",
    name: "Сидемен",
    nights: 2,
    dates: "14–15 июня",
    summary: "Рисовые террасы без туристов, виды на Агунг, детокс",
    emoji: "🌾",
    color: "jungle",
    spots: [
      { name: "Sidemen Rice Terrace Walk", desc: "Прогулка по террасам, фермеры, коровы. Лучше утром", mapQuery: "Sidemen Rice Terrace Walk", tag: "природа", cost: "бесплатно" },
      { name: "Gembleng Waterfall", desc: "Каменные природные ванны-джакузи, 30 мин", mapQuery: "Gembleng Waterfall Sidemen", tag: "водопад", cost: "25k IDR" },
      { name: "Tukad Cepung Waterfall", desc: "Водопад в пещере со столбом света (полдень). 40 мин", mapQuery: "Tukad Cepung Waterfall", tag: "водопад", time: "12–14:00", cost: "20k IDR" },
      { name: "Iseh Viewpoint", desc: "Вид на Агунг", mapQuery: "Iseh Viewpoint Sidemen", tag: "смотровая" },
      { name: "Pura Bukit Tageh", desc: "Небольшой храм на холме, закат", mapQuery: "Pura Bukit Tageh", tag: "храм" },
      { name: "Tenun Pelangi", desc: "Традиционное ткачество эндек, купить шарф", mapQuery: "Tenun Pelangi Sidemen", tag: "ремесло" },
    ],
    cafes: [
      { name: "Sleeping Gajah Kitchen & Lounge", price: "$$$", kitchen: "Ресторан, азиатско-западный фьюжн", desc: "Самое раскрученное место Сидемена у экспатов. Бургеры, пасты, завтраки с беконом. Чек 250k+/чел.", mapQuery: "Sleeping Gajah Kitchen Sidemen", rating: 4.8, reviews: 687 },
      { name: "Warung Ume Anyar", price: "$", kitchen: "Балийская, семейный warung", desc: "Аутентичный семейный варунг. Наси кампур, свежие соки. Блюдо 25–50k, честные цены.", mapQuery: "Warung Ume Anyar Sidemen", rating: 4.6, reviews: 430 },
      { name: "The Sidemen Restaurant", price: "$$$", kitchen: "Ресторан, fine dining", desc: "Особый ужин. Рисовые террасы и лес вокруг. Высокий рейтинг, но отзывов мало (39).", mapQuery: "The Sidemen Restaurant", rating: 4.9, reviews: 39 },
    ],
    workspaces: [],
    workNote: "В Сидемене 0 мест для работы — все кафе open-air (жарко, москиты). Работа только из виллы с AC и надёжным wifi. Либо ехать в Клунгкунг (30 мин) в закрытую кофейню с кондиционером.",
    days: [
      { date: "14 июня", weekday: "вс", title: "Переезд и отдых", isWeekend: true, items: [
        { time: "11:00", text: "Выезд Убуд → Сидемен (1:30)", emoji: "🛵" },
        { time: "13:00", text: "Заселение, обед" },
        { time: "16:00", text: "Прогулка по рисовым террасам" },
        { time: "19:00", text: "Ужин с видом на Агунг" },
      ]},
      { date: "15 июня", weekday: "пн", items: [
        { time: "9:30", text: "Подъём, завтрак в вилле / бассейн" },
        { time: "10:30", text: "Gembleng или Tukad Cepung", emoji: "💦" },
        { time: "13:00", text: "Обед" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "kintamani",
    name: "Кинтамани",
    nights: 5,
    dates: "16–20 июня",
    summary: "🌋 Батур (сб), горячие источники, лава, клубника",
    emoji: "🌋",
    color: "ocean",
    spots: [
      { name: "Mount Batur Sunrise Trek", desc: "Восхождение в 03:00, рассвет 1717 м. С гидом обязательно", mapQuery: "Mount Batur Sunrise Trek", tag: "восхождение", cost: "400–500k IDR с гидом" },
      { name: "Toya Devasya Hot Springs", desc: "Лучшие горячие источники, 4 бассейна + озеро", mapQuery: "Toya Devasya Hot Spring", tag: "спа", cost: "~200k IDR весь день" },
      { name: "Batur Natural Hot Spring", desc: "Бюджетнее Toya Devasya", mapQuery: "Batur Natural Hot Spring", tag: "спа", cost: "125k IDR" },
      { name: "Black Lava Field", desc: "Застывшая лава 1944 года, Pura Jati viewpoint", mapQuery: "Batur Black Lava Field Pura Jati", tag: "природа" },
      { name: "Pura Ulun Danu Batur", desc: "Храм на озере Батур", mapQuery: "Pura Ulun Danu Batur", tag: "храм", cost: "50k" },
      { name: "Kintamani Strawberry Farm", desc: "Собрать клубнику самому", mapQuery: "Kintamani Strawberry Farm", tag: "ферма" },
      { name: "Pancasari Strawberry Farm", desc: "Альтернатива, по дороге в Бедугул", mapQuery: "Pancasari Strawberry Farm", tag: "ферма" },
      { name: "Satria Agrowisata", desc: "Кофейная плантация, бесплатный тур + дегустация", mapQuery: "Satria Agrowisata Kintamani", tag: "кофе", cost: "бесплатно" },
      { name: "Bali Pulina", desc: "Премиум плантация, деревянная смотровая", mapQuery: "Bali Pulina", tag: "кофе", cost: "60k" },
      { name: "Pura Puncak Penulisan", desc: "Храм на вершине горы, вид с высоты", mapQuery: "Pura Puncak Penulisan", tag: "храм" },
      { name: "Trunyan Village", desc: "Деревня на лодке через озеро, необычные обряды", mapQuery: "Trunyan Village", tag: "этно" },
    ],
    cafes: [
      { name: "AKASA", price: "$$", kitchen: "Кофейня, бранч", desc: "Стеклянные павильоны над обрывом к Батуру. Самый раскрученный кафе-кластер Кинтамани. Открыто до 22:00.", mapQuery: "AKASA Kintamani", rating: 4.5, reviews: 10316 },
      { name: "Montana Del Cafe", price: "$$", kitchen: "Индонезийская, бранч, панорама", desc: "Минималистичный кафе со стеклянными стенами и видом на Батур. Смузи-боулы, пасты, бенедикт.", mapQuery: "Montana Del Cafe Kintamani", rating: 4.7, reviews: 6324 },
      { name: "Ritatkala Cafe", price: "$$", kitchen: "Кафе с видом", desc: "Стеклянная стена на Батур. Batur Tea с корицей, завтраки, пиццы, пасты. Откр. с 5:30 к восходу.", mapQuery: "Ritatkala Cafe Kintamani", rating: 4.7, reviews: 3504 },
      { name: "Paperhills", price: "$$", kitchen: "Кофейня, бранч", desc: "Каскадная терраса над кратером в пастельной эстетике. Открывается в 5:30 для встречи восхода.", mapQuery: "Paperhills Kintamani", rating: 4.5, reviews: 3255 },
      { name: "Kintamani Coffee — Eco Bike", price: "$", kitchen: "Кофейня, farm-to-cup", desc: "Кофе делают на месте от сбора до обжарки. Простое меню, тосты, выпечка. Чек 50–75k.", mapQuery: "Kintamani Coffee Eco Bike", rating: 4.6, reviews: 2524 },
      { name: "Blue Mountains Bali", price: "$$", kitchen: "Ресторан, панорама", desc: "Ресторан с высоким рейтингом и видом на Батур. Индонезийская и интернациональная кухня.", mapQuery: "Blue Mountains Bali Kintamani", rating: 4.9, reviews: 1276 },
      { name: "Sisi Gege Restaurant", price: "$$", kitchen: "Кофейня/ресторан, виды", desc: "Смотровая над кальдерой. Работает до 23:00 — один из немногих поздних вариантов. Отзывов пока мало (25).", mapQuery: "Sisi Gege Restaurant Kintamani", rating: 4.8, reviews: 25 },
    ],
    workspaces: [
      { name: "Pahdi Specialty Coffee", type: "Кафе-коворкинг", equipment: "Wifi, розетки, просторный зал, кофе", desc: "Крупнейшая спешелти-кофейня района. Открыто до 22:00. Топ-вариант для работы днём и вечером.", mapQuery: "Pahdi Specialty Coffee Kintamani", rating: 4.6, reviews: 3807, price: "чек 50–100k" },
      { name: "Starbucks Kintamani Bali", type: "Кафе с wifi", equipment: "Wifi, розетки, AC, стандарт Starbucks", desc: "Starbucks с панорамой на Батур. Стабильный wifi, розетки, удобные столы. Открывается в 06:30.", mapQuery: "Starbucks Kintamani Bali", rating: 4.7, reviews: 901, price: "100–150k" },
    ],
    workNote: "Большинство кафе Кинтамани закрываются к 22:00. Для работы до поздней ночи — из отеля.",
    days: [
      { date: "16 июня", weekday: "вт", items: [
        { time: "10:00", text: "Выезд Сидемен → Кинтамани (1:30)", emoji: "🛵" },
        { time: "11:30", text: "Заселение" },
        { time: "12:30", text: "Обед в Akasa с видом" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "17 июня", weekday: "ср", items: [
        { time: "9:30", text: "Завтрак в Hills Break" },
        { time: "10:30", text: "Toya Devasya Hot Springs (2 часа)", emoji: "♨️" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "18 июня", weekday: "чт", items: [
        { time: "9:30", text: "Подъём" },
        { time: "10:30", text: "Клубничная ферма — собрать клубнику", emoji: "🍓" },
        { time: "11:30", text: "Kintamani Coffee Plantation — дегустация" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "19 июня", weekday: "пт", title: "Подготовка к Батуру", items: [
        { time: "10:00", text: "Поздний подъём" },
        { time: "11:00", text: "Pura Ulun Danu Batur" },
        { time: "13:00", text: "Обед" },
        { time: "14:00", text: "Работа до 18:00", emoji: "💻" },
        { time: "19:00", text: "Плотный ужин" },
        { time: "20:00", text: "Лечь спать — ранний старт!" },
      ]},
      { date: "20 июня", weekday: "сб", title: "🌋 БАТУР + отдых", isWeekend: true, items: [
        { time: "02:00", text: "Подъём", emoji: "⏰" },
        { time: "03:00", text: "Старт восхождения на Батур 1717 м", emoji: "🌋", highlight: true },
        { time: "05:30", text: "Рассвет на вершине, завтрак из яиц с пара", highlight: true },
        { time: "07:00", text: "Спуск, обезьяны по пути" },
        { time: "10:00", text: "Возврат в отель, душ, спать" },
        { time: "14:00", text: "Поздний обед" },
        { time: "15:00", text: "Бассейн/спа, восстановление" },
        { time: "18:00", text: "Лёгкий ужин, ранний сон" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "amed",
    name: "Амед",
    nights: 5,
    dates: "21–25 июня",
    summary: "Дайвинг у корабля, массаж, йога, коворкинг, русская баня",
    emoji: "🌊",
    color: "ocean",
    spots: [
      { name: "USS Liberty Shipwreck (Tulamben)", desc: "Must-dive. 2 погружения, 15 мин от Амеда", mapQuery: "USAT Liberty Shipwreck Tulamben", tag: "дайв", time: "6:30 старт", cost: "1M IDR за 2 погружения" },
      { name: "Tirta Gangga Water Palace", desc: "Королевский водный дворец с бассейнами и каменными дорожками-ступеньками среди прудов с карпами. 20 мин от Амеда", mapQuery: "Tirta Gangga Water Palace", tag: "дворец", time: "8:00–10:00 до жары", cost: "50k IDR + 30k парковка" },
      { name: "Japanese Shipwreck Banyuning", desc: "Малый японский корабль, снорк от берега", mapQuery: "Japanese Shipwreck Banyuning Amed", tag: "снорк", cost: "бесплатно" },
      { name: "Jemeluk Bay Viewpoint", desc: "Смотровая, буквы AMED, закат", mapQuery: "Jemeluk Bay Viewpoint Amed", tag: "смотровая" },
      { name: "Blue Earth Village", desc: "Йога утром + коворкинг с видом на Агунг", mapQuery: "Blue Earth Village Amed", tag: "йога/коворкинг", cost: "150k класс" },
      { name: "Serenity Spa Amed", desc: "Массаж с видом", mapQuery: "Serenity Spa Amed", tag: "спа", cost: "250k/час" },
      { name: "Русская баня", desc: "Стеклянная стена, вид на Агунг. Уточнить адрес на месте", mapQuery: "Russian Banya Amed", tag: "баня" },
      { name: "Amed Salt Farms", desc: "Традиционная добыча соли из моря", mapQuery: "Amed Salt Farms", tag: "культура" },
      { name: "Jemeluk Beach Sunrise", desc: "Восход солнца над морем с видом на Агунг", mapQuery: "Jemeluk Beach Amed", tag: "пляж", time: "05:30" },
      { name: "Lipah Beach Sunset", desc: "Закат в сторону моря", mapQuery: "Lipah Beach Amed", tag: "пляж", time: "закат" },
      { name: "Freediving courses", desc: "Топ-место для фри-дайва на Бали", mapQuery: "Apneista Freediving Amed", tag: "фри-дайв" },
    ],
    cafes: [
      { name: "BERINA RICE TERRACE", price: "$", kitchen: "Кафе, рисовые поля", desc: "Рейтинг 5.0 — абсолютный топ Амеда. Чек 25–50k. Откр. с 09:00.", mapQuery: "Berina Rice Terrace Amed", rating: 5.0, reviews: 2236 },
      { name: "Warung Sabar", price: "$", kitchen: "Балийская", desc: "Топовый семейный варунг, 4.9★. Душевная домашняя кухня по низким ценам.", mapQuery: "Warung Sabar Amed", rating: 4.9, reviews: 1447 },
      { name: "Good Stuff Cafe & Eco Store", price: "$$", kitchen: "Ресторан, healthy/веган", desc: "Eco-friendly, dog-friendly. Смузи-боулы, салаты, gluten-free. При кафе эко-магазин.", mapQuery: "Good Stuff Cafe Amed", rating: 4.8, reviews: 1032 },
      { name: "Gusto Resto & Cafe", price: "$$", kitchen: "Пиццерия", desc: "Итальянские блюда, пиццы, пасты. Один из стабильно лучших ресторанов Амеда.", mapQuery: "Gusto Resto Cafe Amed", rating: 4.8, reviews: 1284 },
      { name: "Warung Melasti", price: "$", kitchen: "Ресторан, пляжное", desc: "Пляжное кафе. Чек 50–75k. Завтраки, простые обеды, ноги в песке.", mapQuery: "Warung Melasti Amed", rating: 4.8, reviews: 208 },
      { name: "Food and friends", price: "$", kitchen: "Ресторан, бранч", desc: "Дружелюбная атмосфера. Чек 50–75k. Открывается с 08:00.", mapQuery: "Food and Friends Amed", rating: 4.8, reviews: 249 },
      { name: "Warung Enak and Bungalows", price: "$$", kitchen: "Гест-хаус + ресторан", desc: "Легенда Амеда. Индонезийская классика + пиццы/пасты. Честные цены, адекватное качество.", mapQuery: "Warung Enak Bungalows Amed", rating: 4.6, reviews: 1093 },
      { name: "Rimba Cafe", price: "$$", kitchen: "Ресторан, healthy", desc: "Smoothie bowls, wraps, бургеры, салаты. Витрина мороженого и кондитерской. Откр. с 07:00.", mapQuery: "Rimba Cafe Amed", rating: 4.6, reviews: 2135 },
      { name: "Small Time Cooks", price: "$$", kitchen: "Бургерная", desc: "Культовые бургеры и бао. Быстро, вкусно, много возвращающихся.", mapQuery: "Small Time Cooks Amed", rating: 4.6, reviews: 519 },
      { name: "Trattoria Amed", price: "$$", kitchen: "Итальянская", desc: "Лучшая пицца восточного Бали. Хэнд-мейд пасты, gnocchi, вино. До 22:30.", mapQuery: "Trattoria Amed", rating: 4.5, reviews: 987 },
      { name: "Meeting Point", price: "$", kitchen: "Кафе, бранч", desc: "Популярное кафе на главной улице. Бранчи, бургеры, индонезийская классика.", mapQuery: "Meeting Point Amed", rating: 4.6, reviews: 313 },
    ],
    workspaces: [
      { name: "La Timba", type: "Коворкинг", equipment: "Wifi, розетки, тихо, кофе", desc: "Специализированный коворкинг в Амеде. Работает до 23:00. Рейтинг 4.9, но отзывов пока мало (32).", mapQuery: "La Timba Amed", rating: 4.9, reviews: 32, price: "дневной/недельный пропуск" },
      { name: "Galang Kangin Bungalow & Restaurant", type: "Кафе с wifi", equipment: "Wifi, ресторан, тихо", desc: "Ресторан при гест-хаусе. Wifi, спокойная атмосфера для работы днём.", mapQuery: "Galang Kangin Bungalow Restaurant Amed", rating: 4.5, reviews: 70, price: "средний чек 100–150k" },
    ],
    days: [
      { date: "21 июня", weekday: "вс", title: "Переезд после Батура", isWeekend: true, items: [
        { time: "10:00", text: "Подъём, долгий завтрак" },
        { time: "12:00", text: "Выезд Кинтамани → Амед (2:00)", emoji: "🛵" },
        { time: "14:00", text: "Приехали, заселение" },
        { time: "18:00", text: "Лёгкий ужин у моря" },
      ]},
      { date: "22 июня", weekday: "пн", items: [
        { time: "10:00", text: "Массаж (Serenity / Putri)", emoji: "💆" },
        { time: "12:00", text: "Завтрак в Warung Vienna" },
        { time: "14:00", text: "Работа", emoji: "💻" },
        { time: "18:30", text: "Закат на Jemeluk Bay Viewpoint" },
      ]},
      { date: "23 июня", weekday: "вт", items: [
        { time: "9:00", text: "Йога с видом на Агунг (Blue Earth)", emoji: "🧘" },
        { time: "10:30", text: "Завтрак там же" },
        { time: "14:00", text: "Работа из коворкинга", emoji: "💻" },
      ]},
      { date: "24 июня", weekday: "ср", title: "🤿 Дайвинг Liberty", items: [
        { time: "6:30", text: "Подъём" },
        { time: "7:00", text: "Выезд на дайв-центр" },
        { time: "8:00", text: "Два погружения на USS Liberty", emoji: "🤿", highlight: true },
        { time: "11:30", text: "Возврат, обед в Warung Ocean View" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "25 июня", weekday: "чт", title: "🧖 Русская баня", items: [
        { time: "10:00", text: "Подъём" },
        { time: "11:00", text: "Русская баня со стеклянной стеной", emoji: "🧖", highlight: true },
        { time: "13:00", text: "Обед в Warung Bamboo" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "lovina",
    name: "Ловина",
    nights: 3,
    dates: "26–28 июня",
    summary: "Дельфины, Aling-Aling с прыжками, планктон ночью",
    emoji: "🐬",
    color: "ocean",
    spots: [
      { name: "Dolphin boat tour", desc: "04:30 подъём, лодка, дельфины. Заказать накануне", mapQuery: "Lovina Dolphin Tour", tag: "лодка", time: "05:00", cost: "200k/чел" },
      { name: "Aling-Aling Waterfall", desc: "Must. Прыжки 5/10/15 м, горки, дикий 35-м водопад. Гид обязателен", mapQuery: "Aling-Aling Waterfall", tag: "водопад", cost: "125k с гидом" },
      { name: "Gitgit Waterfall", desc: "Классика, можно совместить с Aling-Aling", mapQuery: "Gitgit Waterfall", tag: "водопад", cost: "20k" },
      { name: "Banjar Hot Springs", desc: "Горячие источники в джунглях", mapQuery: "Banjar Hot Spring", tag: "спа", cost: "20k" },
      { name: "Brahmavihara-Arama", desc: "Буддистский монастырь, 30 мин от Ловины", mapQuery: "Brahmavihara Arama Buleleng", tag: "монастырь", cost: "бесплатно" },
      { name: "Singsing Waterfall", desc: "«Двойной» водопад ближе к Ловине", mapQuery: "Singsing Waterfall Lovina", tag: "водопад" },
      { name: "Kalibukbuk Beach", desc: "Чёрный песок, закат", mapQuery: "Kalibukbuk Beach Lovina", tag: "пляж", time: "закат" },
      { name: "Bioluminescent plankton tour", desc: "Лодка после 21:00, светящийся планктон. Сезон май-август ✓", mapQuery: "Lovina Bioluminescent Plankton Tour", tag: "лодка", time: "21:00+", cost: "~300k/чел" },
      { name: "Les Waterfall (Yeh Mampeh)", desc: "60-м водопад, по пути из Амеда", mapQuery: "Les Waterfall Bali", tag: "водопад" },
    ],
    cafes: [
      { name: "Tanda Pizza Restaurant", price: "$$", kitchen: "Пиццерия", desc: "Лучшая пицца в Ловине — рейтинг 4.9, 1600+ отзывов. Пиццы из дровяной печи, пасты, вино.", mapQuery: "Tanda Pizza Restaurant Lovina", rating: 4.9, reviews: 1623 },
      { name: "Buda Bakery & Resto", price: "$$", kitchen: "Ресторан, пекарня", desc: "Свежий хлеб, торты, выпечка. Обеды: карри, креветки, сэндвичи. Открывается с 08:00.", mapQuery: "Buda Bakery Resto Lovina", rating: 4.7, reviews: 1016 },
      { name: "Secret Garden Restaurant", price: "$$$", kitchen: "Ресторан, healthy", desc: "Уютный сад, healthy-меню. Чек 250k+/чел. Подходит для особого ужина.", mapQuery: "Secret Garden Restaurant Lovina", rating: 4.7, reviews: 646 },
      { name: "Semina Restaurant", price: "$$", kitchen: "Индонезийская", desc: "Айам бетуту, морская паста, сочные бургеры. Один из стабильно лучших ужинов. До 22:30.", mapQuery: "Semina Restaurant Lovina", rating: 4.6, reviews: 427 },
      { name: "Warung Bambu Pemaron", price: "$$", kitchen: "Индонезийская, балийский сет", desc: "Must-try. Сет из 12 балийских блюд, бамбуковый павильон. Открывается с 11:00.", mapQuery: "Warung Bambu Pemaron Lovina", rating: 4.6, reviews: 385 },
      { name: "Lemongrass Resto", price: "$$", kitchen: "Ресторан, тайская", desc: "Тайские и западные блюда. Стабильное место. Откр. с 11:00.", mapQuery: "Lemongrass Resto Lovina", rating: 4.8, reviews: 212 },
      { name: "COFFEENOSKY (Temporary Space)", price: "$$", kitchen: "Кафе, бранч", desc: "Приятная терраса. Круассаны, avo toast, eggs benedict, неплохой кофе.", mapQuery: "Coffeenosky Lovina", rating: 4.5, reviews: 906 },
    ],
    workspaces: [
      { name: "COFFEENOSKY (Temporary Space)", type: "Кафе-коворкинг", equipment: "Wifi, розетки, кофе, столы", desc: "Главное место Ловины для работы. Хороший wifi, комфортные столы, много отзывов.", mapQuery: "Coffeenosky Lovina", rating: 4.5, reviews: 906, price: "средний чек 100–150k" },
      { name: "Cafe Leo", type: "Кафе с wifi", equipment: "Wifi, столы, еда, кофе", desc: "Уютный cafe в центре туристической зоны с бесплатным wifi. Откр. с 07:00.", mapQuery: "Cafe Leo Lovina", rating: 4.7, reviews: 165, price: "70–120k" },
      { name: "Dari coffee & panini", type: "Кафе с wifi", equipment: "Wifi, кофе, panini", desc: "Европейское кафе со спешелти-кофе и panini. Хорошее место для работы на пару часов.", mapQuery: "Dari coffee panini Lovina", rating: 4.8, reviews: 87, price: "60–100k" },
    ],
    days: [
      { date: "26 июня", weekday: "пт", title: "Переезд из Амеда с остановками", items: [
        { time: "7:30", text: "Подъём, завтрак" },
        { time: "8:30", text: "Выезд Амед → Ловина (3:00)", emoji: "🛵" },
        { time: "", text: "Остановки: Tejakula, Les Waterfall 60м, Air Sanih" },
        { time: "13:00", text: "Приехали, заселение, обед" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "27 июня", weekday: "сб", title: "🎯 Aling-Aling + планктон", isWeekend: true, items: [
        { time: "9:00", text: "Завтрак" },
        { time: "10:00", text: "Aling-Aling Waterfall — прыжки 5/10/15 м", emoji: "🎯", highlight: true },
        { time: "13:00", text: "По пути — Gitgit Waterfall" },
        { time: "14:30", text: "Обед в Secret Garden" },
        { time: "18:30", text: "Закат на Kalibukbuk Beach" },
        { time: "20:00", text: "Ужин в Nia Bar" },
        { time: "21:30", text: "Bioluminescent plankton tour", emoji: "🌙", highlight: true },
      ]},
      { date: "28 июня", weekday: "вс", title: "🐬 Дельфины + Banjar", isWeekend: true, items: [
        { time: "4:30", text: "Подъём", emoji: "⏰" },
        { time: "5:00", text: "Лодка на дельфинов", emoji: "🐬", highlight: true },
        { time: "7:00", text: "Завтрак в The Damai / Buddha Banana" },
        { time: "10:00", text: "Banjar Hot Springs", emoji: "♨️" },
        { time: "12:00", text: "Brahmavihara-Arama монастырь" },
        { time: "13:30", text: "Обед, отдых" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "pemuteran",
    name: "Пемутеран",
    nights: 2,
    dates: "29–30 июня",
    summary: "Menjangan Island snorkeling, Biorock, черепахи, тихо",
    emoji: "🐢",
    color: "ocean",
    spots: [
      { name: "Menjangan Island snorkel/dive", desc: "Must. Лучший риф Бали, West Bali National Park. Лодка 8:00, 2–3 часа", mapQuery: "Menjangan Island Bali", tag: "снорк/дайв", cost: "400–600k/чел" },
      { name: "Biorock Pemuteran", desc: "Искусственный коралловый риф у берега, снорк бесплатно", mapQuery: "Biorock Pemuteran Bay", tag: "снорк", cost: "бесплатно" },
      { name: "Reef Seen Turtle Project", desc: "Центр спасения черепах, можно выпустить молодь", mapQuery: "Reef Seen Turtle Project Pemuteran", tag: "черепахи", cost: "~50k" },
      { name: "West Bali National Park", desc: "Джунгли, балийский скворец-эндемик, трекинг", mapQuery: "West Bali National Park", tag: "парк" },
      { name: "Pemuteran Beach sunset", desc: "Чёрный песок, тишина", mapQuery: "Pemuteran Beach", tag: "пляж", time: "закат" },
      { name: "Pulaki Temple", desc: "Храм с семьёй обезьян", mapQuery: "Pulaki Temple Bali", tag: "храм", cost: "бесплатно" },
      { name: "Jayaprana Tomb", desc: "Легендарная могила, смотровая", mapQuery: "Jayaprana Tomb Bali", tag: "смотровая" },
    ],
    cafes: [
      { name: "Quarry", price: "$$", kitchen: "Ресторан, бистро", desc: "Рейтинг 5.0. Современное бистро, стильная атмосфера, европейское меню.", mapQuery: "Quarry Pemuteran", rating: 5.0, reviews: 234 },
      { name: "Warung Sunset", price: "$", kitchen: "Ресторан, закатная атмосфера", desc: "Рейтинг 5.0. Чек 25–50k. Терраса с видом на закат, семейная атмосфера.", mapQuery: "Warung Sunset Pemuteran", rating: 5.0, reviews: 56 },
      { name: "Warung Bukit Pemuteran", price: "$", kitchen: "Балийская", desc: "Варунг с видом. Чек 50–75k. Рейтинг 4.9, аутентичная балийская кухня.", mapQuery: "Warung Bukit Pemuteran", rating: 4.9, reviews: 399 },
      { name: "Lakawi", price: "$", kitchen: "Ресторан", desc: "Рейтинг 4.9. Чек 75–100k. Завтраки, обеды, ужины с видом на океан.", mapQuery: "Lakawi Pemuteran", rating: 4.9, reviews: 453 },
      { name: "K&A Grill", price: "$$", kitchen: "Ресторан, гриль", desc: "Гриль, пасты, салаты, морепродукты. Уютная веранда, 4.8★.", mapQuery: "K&A Grill Pemuteran", rating: 4.8, reviews: 296 },
      { name: "MANTRA SARI RESTO", price: "$$", kitchen: "Индонезийская", desc: "Ресторан индонезийской кухни с высоким рейтингом. Подходит для ежедневного питания.", mapQuery: "Mantra Sari Resto Pemuteran", rating: 4.8, reviews: 268 },
      { name: "The Sage Bali", price: "$$", kitchen: "Ресторан, healthy/веган", desc: "Healthy-блюда с акцентом на веган/вегет. Открывается с 09:00.", mapQuery: "The Sage Bali Pemuteran", rating: 4.8, reviews: 451 },
      { name: "La Casa Kita", price: "$$", kitchen: "Пиццерия", desc: "Пицца из дровяной печи. Ухоженный газон, вечерняя лайв-музыка.", mapQuery: "La Casa Kita Pemuteran", rating: 4.4, reviews: 479 },
    ],
    workspaces: [
      { name: "Warung Bukit Pemuteran", type: "Кафе с wifi", equipment: "Wifi, вид, кофе", desc: "Рейтинг 4.9. Единственный адекватный вариант в Пемутеране для работы с ноутом. Вечером — из отеля.", mapQuery: "Warung Bukit Pemuteran", rating: 4.9, reviews: 399, price: "50–75k" },
    ],
    workNote: "В Пемутеране практически нет мест для серьёзной работы. Вечером — только из отеля (Matahari Beach, Taman Sari, Puri Ganesha).",
    days: [
      { date: "29 июня", weekday: "пн", items: [
        { time: "10:00", text: "Выезд Ловина → Пемутеран (1:15)", emoji: "🛵" },
        { time: "11:30", text: "Заселение" },
        { time: "12:00", text: "Biorock — снорк у берега", emoji: "🐠" },
        { time: "12:30", text: "Reef Seen Turtle Project", emoji: "🐢" },
        { time: "13:30", text: "Обед в Warung Kayu Manis" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "30 июня", weekday: "вт", title: "🤿 Menjangan Island", items: [
        { time: "7:00", text: "Подъём, лёгкий завтрак" },
        { time: "7:30", text: "На пирсе, лодка в West Bali NP" },
        { time: "8:00", text: "Snorkel / dive Menjangan", emoji: "🤿", highlight: true },
        { time: "12:30", text: "Возврат, обед в Seasalt" },
        { time: "14:00", text: "Работа", emoji: "💻" },
        { time: "19:00", text: "Ужин в The Kawi" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "munduk",
    name: "Мундук",
    nights: 3,
    dates: "1–3 июля",
    summary: "Водопады, озёра Буян/Тамблинган, храм Ulun Danu Beratan",
    emoji: "⛰",
    color: "jungle",
    spots: [
      { name: "Munduk Waterfall", desc: "Классика, лёгкий трек 15 мин", mapQuery: "Munduk Waterfall", tag: "водопад", cost: "20k" },
      { name: "Melanting Waterfall", desc: "Рядом с Мундук-водопадом, совмещённый трек", mapQuery: "Melanting Waterfall Munduk", tag: "водопад" },
      { name: "Red Coral Waterfall", desc: "Малоизвестный, фотогеничный", mapQuery: "Red Coral Waterfall Munduk", tag: "водопад" },
      { name: "Banyumala Twin Waterfall", desc: "Двойной водопад, одно из самых красивых мест Бали", mapQuery: "Banyumala Twin Waterfall", tag: "водопад", cost: "30k" },
      { name: "Twin Lakes Viewpoint (Wanagiri)", desc: "Панорама на Буян и Тамблинган", mapQuery: "Twin Lake Viewpoint Munduk", tag: "смотровая" },
      { name: "Wanagiri Hidden Hills", desc: "«Гнёзда» и качели для фото", mapQuery: "Wanagiri Hidden Hills", tag: "фото", cost: "50k" },
      { name: "Danau Buyan", desc: "Прогулка по берегу, каноэ", mapQuery: "Danau Buyan Bali", tag: "озеро" },
      { name: "Danau Tamblingan", desc: "Тихое священное озеро, каноэ", mapQuery: "Danau Tamblingan", tag: "озеро" },
      { name: "Pura Ulun Danu Beratan", desc: "Легендарный храм на озере. MUST на закате. 30 мин от Мундука", mapQuery: "Ulun Danu Beratan Temple", tag: "храм", time: "закат", cost: "75k" },
      { name: "Bali Handara Gate", desc: "Инстаграмные «ворота в небо». Очередь за фото 20 мин", mapQuery: "Bali Handara Gate", tag: "фото", cost: "50k" },
      { name: "Munduk Village Walk", desc: "Прогулка по деревне с гидом", mapQuery: "Munduk Village", tag: "прогулка" },
    ],
    cafes: [],
    workspaces: [],
    workNote: "Мундук — горная деревня. Еду и wifi ищи в отеле (Ngiring Ngewedang, Puri Lumbung и др.) либо перезагружайся тут без работы.",
    days: [
      { date: "1 июля", weekday: "ср", items: [
        { time: "9:00", text: "Выезд Пемутеран → Мундук (2:30)", emoji: "🛵" },
        { time: "11:30", text: "Заселение" },
        { time: "12:00", text: "Обед в Ngiring Ngewedang" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "2 июля", weekday: "чт", title: "Водопады", items: [
        { time: "9:30", text: "Завтрак в Don Biyu" },
        { time: "10:30", text: "Munduk + Melanting водопады (1.5 ч)", emoji: "💦" },
        { time: "14:00", text: "Работа", emoji: "💻" },
      ]},
      { date: "3 июля", weekday: "пт", title: "Озёра + храм на закат", items: [
        { time: "9:00", text: "Подъём" },
        { time: "10:00", text: "Twin Lakes Viewpoint" },
        { time: "10:30", text: "Wanagiri Hidden Hills (20 мин)" },
        { time: "11:30", text: "Banyumala Twin Waterfall", emoji: "💦" },
        { time: "14:00", text: "Работа", emoji: "💻" },
        { time: "18:00", text: "Pura Ulun Danu Beratan на закате", emoji: "🏯", highlight: true },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "jatiluwih",
    name: "Джатилувих",
    nights: 2,
    dates: "4–5 июля",
    summary: "UNESCO террасы, храм Батукару, тишина",
    emoji: "🌾",
    color: "jungle",
    spots: [
      { name: "Jatiluwih Rice Terraces", desc: "UNESCO. Трек-маршруты (красный/жёлтый/синий), 1–3 часа", mapQuery: "Jatiluwih Rice Terrace", tag: "природа", cost: "40k вход" },
      { name: "Pura Luhur Batukaru", desc: "Второй по значимости храм после Besakih, среди джунглей", mapQuery: "Pura Luhur Batukaru", tag: "храм", cost: "бесплатно, донат" },
      { name: "Leke Leke Waterfall", desc: "Спрятанный водопад в джунглях, 40 мин", mapQuery: "Leke Leke Waterfall", tag: "водопад", cost: "50k" },
      { name: "Yeh Hoo Waterfall", desc: "Каскад, мало людей", mapQuery: "Yeh Hoo Waterfall", tag: "водопад" },
      { name: "Gunung Batukaru trek", desc: "Восхождение 2276м, серьёзный трек (для энтузиастов)", mapQuery: "Mount Batukaru", tag: "трек" },
      { name: "Pupuan Rice Terraces", desc: "Ещё одни террасы, менее известные", mapQuery: "Pupuan Rice Terrace", tag: "природа" },
      { name: "Cycling по террасам", desc: "Велопрокат при Jatiluwih Visitor Center", mapQuery: "Jatiluwih Visitor Center", tag: "вело" },
    ],
    cafes: [],
    workspaces: [],
    workNote: "Джатилувих — заповедник рисовых террас. Работы и еды здесь минимум, большинство точек при входе в парк. Ешь и работай из отеля.",
    days: [
      { date: "4 июля", weekday: "сб", title: "🎯 Террасы + храм Батукару", isWeekend: true, items: [
        { time: "8:30", text: "Завтрак" },
        { time: "9:30", text: "Выезд Мундук → Джатилувих (1:30)", emoji: "🛵" },
        { time: "11:00", text: "Заселение" },
        { time: "11:30", text: "Jatiluwih Rice Terraces trekking", emoji: "🌾", highlight: true },
        { time: "13:30", text: "Обед в Gong Jatiluwih с панорамой" },
        { time: "15:00", text: "Pura Luhur Batukaru — храм в джунглях", emoji: "🏯", highlight: true },
        { time: "19:00", text: "Ужин" },
      ]},
      { date: "5 июля", weekday: "вс", title: "Водопад + отдых", isWeekend: true, items: [
        { time: "9:30", text: "Бассейн, завтрак" },
        { time: "11:00", text: "Leke Leke Waterfall (40 мин)", emoji: "💦" },
        { time: "13:00", text: "Обед в DHistory / Sang Giri" },
        { time: "14:00", text: "Отдых, прогулка по террасам" },
        { time: "18:00", text: "Закат на террасах" },
        { time: "20:00", text: "Ужин при свечах / костёр" },
      ]},
    ],
  },

  // =========================================================
  {
    slug: "seminyak",
    name: "Семиньяк",
    nights: 2,
    dates: "6–7 июля",
    summary: "Буфер перед вылетом, закаты, прощальный ужин",
    emoji: "🏖",
    color: "sunset",
    spots: [
      { name: "Potato Head Beach Club", desc: "Must. Закат, архитектура", mapQuery: "Potato Head Beach Club", tag: "beach club", time: "закат" },
      { name: "La Brisa Canggu", desc: "Beach club био-стиль", mapQuery: "La Brisa Canggu", tag: "beach club", time: "закат" },
      { name: "Seminyak Beach", desc: "Длинный пляж у Potato Head", mapQuery: "Seminyak Beach", tag: "пляж" },
      { name: "Seminyak Square", desc: "Шопинг, бренды", mapQuery: "Seminyak Square", tag: "шопинг" },
      { name: "Double Six Beach", desc: "Пляж с barlife", mapQuery: "Double Six Beach", tag: "пляж" },
      { name: "Tanah Lot", desc: "Храм на скале, 40 мин от Семиньяка, закат", mapQuery: "Tanah Lot", tag: "храм", time: "закат", cost: "60k" },
      { name: "Ku De Ta", desc: "Легендарный beach club", mapQuery: "Ku De Ta Seminyak", tag: "beach club" },
      { name: "Petitenget Beach", desc: "Тише, без толпы", mapQuery: "Petitenget Beach", tag: "пляж" },
    ],
    cafes: [],
    workspaces: [],
    workNote: "Семиньяк — буфер перед вылетом на 2 ночи. Конкретные места не нужны, выбирай по настроению.",
    days: [
      { date: "6 июля", weekday: "пн", items: [
        { time: "10:00", text: "Выезд Джатилувих → Семиньяк (2:00)", emoji: "🛵" },
        { time: "12:00", text: "Заселение" },
        { time: "13:00", text: "Обед в Sisterfields" },
        { time: "14:00", text: "Работа", emoji: "💻" },
        { time: "20:00", text: "Ужин в La Lucciola" },
      ]},
      { date: "7 июля", weekday: "вт", title: "Прощание с Бали", items: [
        { time: "9:30", text: "Бассейн / пляж" },
        { time: "11:00", text: "Шопинг на Seminyak Square" },
        { time: "14:00", text: "Работа (последний день)", emoji: "💻" },
        { time: "18:00", text: "Закат в Potato Head / La Brisa", emoji: "🌅", highlight: true },
        { time: "20:30", text: "Прощальный ужин: Merah Putih / Sarong / Mama San" },
      ]},
    ],
  },
];

export function getPlace(slug: string): Place | undefined {
  return PLACES.find((p) => p.slug === slug);
}
